import { NavItem, User, CheckRequest, CheckStatus, Service, GasRequest, ServiceStatus } from './types';

export const VALID_NEXT_STATUS: Record<ServiceStatus, ServiceStatus[]> = {
  'Registrado':   ['Asignado'],
  'Asignado':     ['En camino'],
  'En camino':    ['En proceso'],
  'En proceso':   ['Reprogramado', 'Terminado'],
  'Reprogramado': ['Asignado'],
  'Terminado':    []
};

export const USER_DIRECTORY: User[] = [
  { email:'luis.hernandez@servnet.mx',    nombre:'Luis Manuel de la Rosa Hernandez',    region:'CMX', alias:'Raptor',      rol:'CUADRILLA',      tarjeta:'4195', activo:true },
  { email:'victor.arredondo@servnet.mx',  nombre:'Victor Alejandro Arredondo Rangel',   region:'MTY', alias:'Dynamo',      rol:'CUADRILLA',      tarjeta:'9329', activo:true },
  { email:'carlos.capistran@servnet.mx',  nombre:'Carlos Alberto Capistran Ortega',     region:'MTY', alias:'Megatron',    rol:'CUADRILLA',      tarjeta:'',     activo:true },
  { email:'martin.bernal@servnet.mx',     nombre:'Martin Giovanni Bernal Perez',        region:'CMX', alias:'SilentFiber', rol:'CUADRILLA',      tarjeta:'4435', activo:true },
  { email:'enrique.rodriguez@servnet.mx', nombre:'Luis Enrique Rodriguez Aguilera',     region:'CMX', alias:'Kraken',      rol:'CUADRILLA',      tarjeta:'4369', activo:true },
  { email:'ricardo.hernandez@servnet.mx', nombre:'Ricardo Hernandez Alcala',            region:'CMX', alias:'Pegaso',      rol:'CUADRILLA',      tarjeta:'9287', activo:true },
  { email:'jorge.sauceda@servnet.mx',     nombre:'Jorge Ivan Sauceda Gaona',            region:'QRO', alias:'Neptuno',     rol:'CUADRILLA',      tarjeta:'',     activo:true },
  { email:'mauricio.mendiola@servnet.mx', nombre:'Mauricio Mendiola Marcelino',         region:'CMX', alias:'Eastman',     rol:'CUADRILLA',      tarjeta:'',     activo:true },
  { email:'octavio.marquez@servnet.mx',   nombre:'José Octavio Márquez Vazquez',        region:'CMX', alias:'Octopus',     rol:'CUADRILLA',      tarjeta:'',     activo:true },
  { email:'erika.fernandez@servnet.mx',   nombre:'Erika Fernández Lomas',               region:'CMX', alias:'',            rol:'ADMINISTRADOR',  tarjeta:'4146', activo:true },
  { email:'samantha.escamilla@servnet.mx',nombre:'Samantha Escamilla Belman',           region:'CMX', alias:'',            rol:'ADMINISTRADOR',  tarjeta:'9295', activo:true },
  { email:'zuriel.macias@servnet.mx',     nombre:'Andrés Zuriel Macías Ríos',           region:'CMX', alias:'',            rol:'ADMINISTRADOR',  tarjeta:'9477', activo:true },
  { email:'filiberto.altamirano@servnet.mx',nombre:'Filiberto Altamirano Aguirre',      region:'CMX', alias:'',            rol:'ADMINISTRADOR',  tarjeta:'4161', activo:true },
  { email:'elidan.aguirre@servnet.mx',    nombre:'Elidan Aguirre Ortiz',                region:'CMX', alias:'',            rol:'ADMINISTRADOR',  tarjeta:'4070', activo:true },
  { email:'andrea.barrera@servnet.mx',    nombre:'Andrea Barrera Esparza',              region:'CMX', alias:'',            rol:'ADMINISTRADOR',  tarjeta:'9550', activo:true },
  { email:'marco.garcia@servnet.mx',      nombre:'Marco Antonio Garcia Fragoso',        region:'CMX', alias:'',            rol:'ADMINISTRADOR',  tarjeta:'4419', activo:true },
  { email:'gerardo.gomez@servnet.mx',     nombre:'Gerardo Gomez Zavala',                region:'CMX', alias:'',            rol:'ADMINISTRADOR',  tarjeta:'4187', activo:true },
  { email:'alfonso.enriquez@servnet.mx',  nombre:'Alfonso Enriquez Guerrero',           region:'CMX', alias:'',            rol:'ADMINISTRADOR',  tarjeta:'4021', activo:true },
  { email:'nahum.salgado@servnet.mx',     nombre:'Nahum Salgado',                       region:'CMX', alias:'',            rol:'ADMINISTRADOR',  tarjeta:'',     activo:true },
  { email:'hilario.garcia@servnet.mx',    nombre:'Hilario Garcia',                      region:'CMX', alias:'',            rol:'ADMINISTRADOR',  tarjeta:'',     activo:true },
  { email:'marcos.ordonez@servnet.mx',    nombre:'Marcos Ordoñez',                      region:'CMX', alias:'',            rol:'ADMINISTRADOR',  tarjeta:'',     activo:true },
  { email:'operaciones.master@servnet.mx',nombre:'Operaciones Master',                  region:'CMX', alias:'',            rol:'ADMINISTRADOR',  tarjeta:'1',    activo:true },
];

export const NAV_ITEMS: NavItem[] = [
  { id: 'mis-asignaciones', label: 'Mis Asignaciones' },
  { id: 'check-in-out', label: 'Check In/Out' },
  { id: 'servicios', label: 'Servicios' },
  { id: 'solicitud-gasolina', label: 'Solicitud de Gasolina' },
  { id: 'comprobacion-gastos', label: 'Comprobación de Gastos' },
  { id: 'gestion-horas-extras', label: 'Gestión de Horas Extras' },
  { id: 'gestion-cuadrillas', label: 'Gestión de Cuadrillas' },
  { id: 'ubicacion-pops', label: 'Ubicación de PoPs' },
  { id: 'cierre-empalme', label: 'Cierre de Empalme' },
  { id: 'sla', label: 'SLA' },
  { id: 'gestion-usuarios', label: 'Gestión de Usuarios' }
];

export const CHECK_STATUS_OPTIONS: CheckStatus[] = ['En revisión', 'Autorizado', 'Rechazado', 'Pagado'];

export const SQUAD_ALIASES = [
  'Nemo', 'Raptor', 'SilentFiber', 'Pegaso', 'Barracuda', 'Phoenix',
  'Octopus', 'Dynamo', 'Megatron', 'Kraken', 'Poseidón', 'Neptuno',
  'Eastman', 'Fibonacci', 'PacketLoss', 'Jitter', 'Optimus', 'Britmor'
];

export const MOCK_CHECKS: CheckRequest[] = [
  {
    id: '88317557',
    email: 'ricardo.hernandez@servnet.mx',
    cuadrilla: 'Pegaso',
    timeCheckIn: '2026-05-11T06:31:36',
    timeCheckOut: '2026-05-11T18:12:53',
    checkInLocation: { lat: 19.444045, lng: -99.204560 },
    checkOutLocation: { lat: 19.444245, lng: -99.204660 },
    status: 'En revisión',
    horasAutorizadas: 0,
    comentarios: ''
  },
  {
    id: '2bf6aadd',
    email: 'luis.hernandez@servnet.mx',
    cuadrilla: 'Raptor',
    timeCheckIn: '2026-05-11T07:45:37',
    timeCheckOut: '2026-05-11T16:30:00',
    checkInLocation: { lat: 19.432608, lng: -99.133209 },
    status: 'Autorizado',
    horasAutorizadas: 8.5,
    comentarios: 'Todo en orden'
  },
  {
    id: 'fe4aabef',
    email: 'octavio.marquez@servnet.mx',
    cuadrilla: 'Octopus',
    timeCheckIn: '2026-05-11T07:54:09',
    checkInLocation: { lat: 19.400000, lng: -99.150000 },
    status: 'En revisión',
    horasAutorizadas: 0,
    comentarios: ''
  },
  {
    id: 'b1a44830',
    email: 'martin.bernal@servnet.mx',
    cuadrilla: 'SilentFiber',
    timeCheckIn: '2026-05-11T08:05:23',
    checkInLocation: { lat: 19.350000, lng: -99.200000 },
    status: 'En revisión',
    horasAutorizadas: 0,
    comentarios: ''
  },
  {
    id: '733ba963',
    email: 'victor.arredondo@servnet.mx',
    cuadrilla: 'Dynamo',
    timeCheckIn: '2026-05-11T08:21:37',
    checkInLocation: { lat: 25.6866, lng: -100.3161 },
    status: 'En revisión',
    horasAutorizadas: 0,
    comentarios: ''
  },
  {
    id: '1b107b9e',
    email: 'jorge.sauceda@servnet.mx',
    cuadrilla: 'Neptuno',
    timeCheckIn: '2026-10-05T06:06:54',
    timeCheckOut: '2026-10-05T16:03:09',
    checkInLocation: { lat: 20.6139, lng: -100.3886 },
    status: 'Pagado',
    horasAutorizadas: 10,
    comentarios: 'Pago quincena 1'
  },
  {
    id: 'ef696cad',
    email: 'mauricio.mendiola@servnet.mx',
    cuadrilla: 'Eastman',
    timeCheckIn: '2026-05-09T09:41:27',
    timeCheckOut: '2026-05-09T17:49:49',
    checkInLocation: { lat: 19.4326, lng: -99.1332 },
    status: 'Autorizado',
    horasAutorizadas: 8,
    comentarios: ''
  },
  {
    id: 'd569fdc5',
    email: 'mauricio.mendiola@servnet.mx',
    cuadrilla: 'Eastman',
    timeCheckIn: '2026-08-05T07:14:50',
    timeCheckOut: '2026-08-05T21:40:12',
    checkInLocation: { lat: 19.4326, lng: -99.1332 },
    status: 'En revisión',
    horasAutorizadas: 0,
    comentarios: ''
  }
];

export const CATEGORY_PREFIXES: Record<string, string> = {
  'Factibilidad en sitio': 'SS',
  'Scouting': 'SCOUT',
  'Ingreso de vehiculo al taller': 'INGVT',
  'Ingenieria de cierre y continuidad': 'IC',
  'Abasto de materiales': 'ABM',
  'Auditoria de cuadrillas': 'AUDC',
  'Trabajo de escritorio': 'TE',
  'Capacitación': 'CAP',
  'Recolección de equipos': 'RE',
  'Actividad en Guardia': 'GUA',
  'Apoyo general a otras áreas': 'AGOA',
  'Auditoria de Pop': 'AUDPOP',
  'Falla CFE en POP': 'FCFE',
  'Servicio fuera de tiempo': 'SFT',
  'Incidencia menor': 'INC',   'Incidencia mayor': 'INC',
  'Mantenimiento menor en Pop': 'MPOP', 'Mantenimiento mayor en Pop': 'MPOP',
  'Instalación menor': 'INST', 'Instalación mayor': 'INST',
  'Mantenimiento menor de rutas fibra': 'MRF',
  'Mantenimiento mayor de rutas fibra': 'MRF',
  'Desinstalación de equipos o cableado menor': 'DESINST',
  'Desinstalación de equipos o cableado mayor': 'DESINST',
  'Upgrade menor': 'UPG', 'Upgrade mayor': 'UPG',
  'Ventana de mantenimiento Cliente menor': 'VMC',
  'Ventana de mantenimiento Cliente mayor': 'VMC',
  'Cambio de domicilio menor': 'CAMD',
  'Cambio de domicilio mayor': 'CAMD',
};

export const CATEGORY_POINTS: Record<string, number> = {
  'Abasto de materiales': 1, 'Recolección de equipos': 1,
  'Incidencia menor': 1, 'Mantenimiento menor en Pop': 1,
  'Instalación menor': 1, 'Ingenieria de cierre y continuidad': 1,
  'Auditoria de cuadrillas': 1, 'Trabajo de escritorio': 1,
  'Capacitación': 1, 'Mantenimiento menor de rutas fibra': 1,
  'Desinstalación de equipos o cableado menor': 1,
  'Auditoria de Pop': 1, 'Upgrade menor': 1,
  'Ingreso de vehiculo al taller': 1, 'Cambio de domicilio menor': 1,
  'Apoyo general a otras áreas': 1, 'Factibilidad en sitio': 2,
  'Scouting': 2, 'Instalación mayor': 2, 'Mantenimiento mayor en Pop': 2,
  'Mantenimiento mayor de rutas fibra': 2,
  'Desinstalación de equipos o cableado mayor': 2,
  'Upgrade mayor': 2, 'Ventana de mantenimiento Cliente menor': 2,
  'Ventana de mantenimiento Cliente mayor': 2,
  'Cambio de domicilio mayor': 2, 'Ventana de mantenimiento menor en POP': 2,
  'Incidencia mayor': 3, 'Falla CFE en POP': 3,
  'Ventana de mantenimiento mayor en POP': 5, 'Actividad en Guardia': 5,
};

export const POPS_LIST = [
  'MTY-002-LOMA LARGA','MTY-007-ESTRADA','MTY-008-TORRE CYTRO',
  'MTY-009-GARCÍA','EMX-004-TOLUCA 3','EMX-010-ARENILLAS',
  'EMX-018-NAUCALPAN','EMX-019-TOLUCA_AERO','CMX-020-LA IBERO',
  'EMX-022-TOLUCA_QST','CMX-025-NEXTENGO','CMX-026-SANTA FE 01',
  'CMX-032-CIRION','EMX-005-JAHUEYES','EMX-023-CUAUTITLAN IZCALLI',
  'EMX-025-ORION','CMX-027-SANTA FE 02','EMX-013-NICOLAS ROMERO',
  'CMX-028-KIO MEX/2','EMX-029-TLACOLTEPEC','HID-001-OLMOS',
  'HID-002-TULA','MTY-003-ANODIZE','MTY-004-CENTRAL SEMILLERO',
  'MTY-005-LA ESTANZUELA','QRO-001-BUENAVISTA','QRO-002-QUERETARO 1',
  'EMX-007-EL ROSAL','EMX-008-JILOTEPEC 2','GDL-001-GUADALAJARA',
  'GDL-002-GUADALAJARA 1','EMX-009-JILOTEPEC','QRO-003-CASA BLANCA',
  'QRO-004-CHROMAFLO','QRO-005-QUERETARO 2','QRO-006-CONNIN',
  'QRO-007-LOMA DEL CHINO','QRO-008-EQUINIX','EMX-001-SIDERAL',
  'EMX-002-ATIZAPAN','PUE-001-PUEBLA','EMX-012-TLALNEMEX',
  'CMX-030-SAN JUAN-DATACENTER','CMX-016-AZCAPOTZALCO',
  'EMX-021-TEXCOCO','HID-003-QUMA','EMX-011-TULTEPEC',
  'MOR-001-CUERNAVACA 3','MOR-002-CUERNAVACA 1','MOR-003-CUERNAVACA 4',
  'CMX-005-AZTECA','PUE-002-ATLIXCO','CMX-013-AJUSCO',
  'EMX-014-LA QUEBRADA','EMX-015-CHICONAUTLA','MOR-006-CUERNAVACA 2',
  'CMX-004-TACUBA','CMX-008-IZAZAGA','CMX-009-CONSTITUYENTES 3',
  'CMX-012-RIO LERMA','EMX-016-CHIMALHUACAN','CMX-014-ROMA NORTE',
  'CMX-018-DOWN TOWN','EMX-024-CUATRO VIENTOS','CMX-034-NARVARTE',
  'CMX-001-PRESA FALCON','CMX-002-HERSCHEL','CMX-011-ARAGÓN-2',
  'CMX-015-ARAGÓN-1','CMX-019-EDIFICIO CASTELAR',
  'CMX-021-SANTA MARIA INSURGENTES','CMX-022-TORRE LATINO',
  'HID-004-TEPEAPULCO','CMX-033-SAN RAFAEL','EMX-017-JOCOTITLAN',
  'CMX-030-LA QUEBRADA',
];

export const MOCK_SERVICES: Service[] = [
  {
    id: 'INST-1486',
    nombre: 'Supervisar el tendido de F.O de la Quebrada',
    fechaCreacion: '2026-05-11T08:26:06',
    creadoPor: 'carlos.martinez@servnet.mx',
    cuadrillaAlias: 'SilentFiber',
    fechaInicio: '2026-05-12T09:00:00',
    status: 'Asignado',
    statusHistory: [
      { status: 'Registrado', timestamp: '2026-05-11T08:26:06Z' },
      { status: 'Asignado', timestamp: '2026-05-11T08:30:12Z' }
    ],
    prioridad: 'Alta',
    estado: 'Nuevo servicio',
    categoria: 'Instalación mayor',
    statusServicio: 'En tiempo',
    tipoTecnologia: 'Fibra óptica',
    actividadARealizar: 'Favor de supervisar el tendido de F.O del pop la quebrada en el punto donde se quedo el dia de ayer',
    ticketWSAS: 'WSAS-9921',
    team: 'OSP CMX',
    razonSocialCliente: 'Servnet S.A. de C.V.',
    direccionCliente: 'Calle Falsa 123',
    pop: 'CMX-030-LA QUEBRADA',
    identificador: 'ID-4421',
    referenciasUbicacion: 'Cerca del metro',
    nombreContacto: 'Carlos Perez',
    telefonoContacto: '5512345678',
    emailContacto: 'carlos@cliente.com',
    qr: 'http://qrcode.com/123',
    color: '#1a73e8',
    esEventoDia: false,
    horaEnCamino: '2026-05-12T08:30:00',
    horaLlegada: '2026-05-12T09:15:00',
    fechaFin: '2026-05-12T17:45:00'
  },
  {
    id: 'INST-1485',
    nombre: 'Tendido de fibra Pop Telmex',
    fechaCreacion: '2026-05-11T09:00:11',
    creadoPor: ' nahum.salgado@servnet.mx',
    cuadrillaAlias: 'Fibonacci',
    fechaInicio: '2026-05-12T09:00:11',
    fechaFin: '2026-05-12T13:00:11',
    status: 'Registrado',
    statusHistory: [
      { status: 'Registrado', timestamp: '2026-05-11T09:00:11Z' }
    ],
    prioridad: 'Media',
    estado: 'Nuevo servicio',
    categoria: 'Instalación mayor',
    statusServicio: 'En tiempo',
    tipoTecnologia: 'Fibra óptica',
    actividadARealizar: 'Favor de rematar la F.O',
    ticketWSAS: 'WSAS-8812',
    team: 'OSP CMX',
    razonSocialCliente: 'Telmex',
    direccionCliente: 'Av. Insurgentes Sur 1202',
    pop: 'CMX-012-RIO LERMA',
    identificador: 'ID-8812',
    referenciasUbicacion: 'Piso 4',
    nombreContacto: 'Juan Gomez',
    telefonoContacto: '5566778899',
    emailContacto: 'juan@telmex.com',
    qr: 'http://qrcode.com/456',
    color: '#34a853',
    esEventoDia: false
  },
  {
    id: 'ABM-333',
    nombre: 'RECOLECCION MATERIAL MTY',
    fechaCreacion: '2026-05-12T10:00:00',
    creadoPor: 'nahum.salgado@servnet.mx',
    cuadrillaAlias: 'Megatron',
    fechaInicio: '2026-05-12T12:00:00',
    fechaFin: '2026-05-12T15:00:00',
    status: 'En proceso',
    statusHistory: [
      { status: 'Registrado', timestamp: '2026-05-12T10:00:00Z' },
      { status: 'Asignado', timestamp: '2026-05-12T10:15:00Z' },
      { status: 'En camino', timestamp: '2026-05-12T11:45:00Z' },
      { status: 'En proceso', timestamp: '2026-05-12T12:05:00Z' }
    ],
    prioridad: 'Baja',
    estado: 'Activo',
    categoria: 'Abasto de materiales',
    statusServicio: 'En tiempo',
    tipoTecnologia: 'Fibra óptica',
    actividadARealizar: 'Carga de carrete',
    ticketWSAS: '',
    team: 'OSP MTY',
    razonSocialCliente: 'Almacen MTY',
    direccionCliente: 'Regio Almacen 1',
    pop: 'MTY-009-GARCÍA',
    identificador: 'ALM-001',
    referenciasUbicacion: '',
    nombreContacto: 'Pedro Regio',
    telefonoContacto: '8112345678',
    emailContacto: 'pedro@mty.mx',
    qr: 'http://',
    color: '#f4b400',
    esEventoDia: false
  }
];

export const MOCK_GAS_REQUESTS: GasRequest[] = [
  {
    id: 'GAS-001',
    tipoSolicitud: 'Normal',
    asignacionUso: 'Unidad móvil',
    solicitante: 'gerardo.gomez@servnet.mx',
    fechaHr: '2026-05-11 09:55:03',
    status: 'Dispersado',
    cuadrilla: 'Britmor',
    tarjeta: '1318820',
    fotoTableroAntes: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&q=80&w=100',
    kilometrajeAntes: 340136,
    cargaMxn: 1000,
    cargaAutorizada: 1000,
    comentarios: ''
  },
  {
    id: 'GAS-002',
    tipoSolicitud: 'Normal',
    asignacionUso: 'Unidad móvil',
    solicitante: 'gerardo.gomez@servnet.mx',
    fechaHr: '2026-05-11 09:54:52',
    status: 'Dispersado',
    cuadrilla: 'Britmor',
    tarjeta: '1318820',
    fotoTableroAntes: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&q=80&w=100',
    kilometrajeAntes: 339915,
    cargaMxn: 800,
    cargaAutorizada: 800,
    comentarios: ''
  },
  {
    id: 'GASPE-001',
    tipoSolicitud: 'Normal',
    asignacionUso: 'Planta de Emergencia',
    solicitante: 'luis.hernandez@servnet.mx',
    fechaHr: '2026-05-11 17:22:39',
    status: 'Cargado/Comprobación',
    cuadrilla: 'Raptor',
    tarjeta: '1420602',
    fotoTableroAntes: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=100',
    kilometrajeAntes: 1,
    cargaMxn: 500,
    cargaAutorizada: 500,
    comentarios: 'Carga para planta emex',
    ticketEfectivale: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&q=80&w=100',
    ticketBomba: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&q=80&w=100',
    bombaCargando: 'https://images.unsplash.com/photo-1545161296-d9c2c241f2ad?auto=format&fit=crop&q=80&w=100',
    fotoTableroDespues: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=100'
  },
  {
    id: 'GAS-003',
    tipoSolicitud: 'Normal',
    asignacionUso: 'Unidad móvil',
    solicitante: 'luis.hernandez@servnet.mx',
    fechaHr: '2026-05-18 15:23:33',
    status: 'Cargado/Comprobación',
    cuadrilla: 'Raptor',
    tarjeta: '1420602',
    fotoTableroAntes: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&q=80&w=100',
    kilometrajeAntes: 1420602,
    cargaMxn: 1200,
    cargaAutorizada: 1200,
    comentarios: 'Ruta foranea',
    ticketEfectivale: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&q=80&w=100',
    ticketBomba: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&q=80&w=100',
    bombaCargando: 'https://images.unsplash.com/photo-1545161296-d9c2c241f2ad?auto=format&fit=crop&q=80&w=100',
    fotoTableroDespues: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&q=80&w=100'
  },
  {
    id: 'GAS-004',
    tipoSolicitud: 'Normal',
    asignacionUso: 'Unidad móvil',
    solicitante: 'luis.hernandez@servnet.mx',
    fechaHr: '2026-05-11 16:24:53',
    status: 'Cargado/Comprobación',
    cuadrilla: 'Raptor',
    tarjeta: '1420602',
    fotoTableroAntes: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&q=80&w=100',
    kilometrajeAntes: 113759,
    cargaMxn: 1000,
    cargaAutorizada: 1000,
    comentarios: '',
    ticketEfectivale: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&q=80&w=100',
    ticketBomba: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&q=80&w=100',
    bombaCargando: 'https://images.unsplash.com/photo-1545161296-d9c2c241f2ad?auto=format&fit=crop&q=80&w=100',
    fotoTableroDespues: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&q=80&w=100'
  },
  {
    id: 'GAS-005',
    tipoSolicitud: 'Normal',
    asignacionUso: 'Unidad móvil',
    solicitante: 'esai.moreno@servnet.mx',
    fechaHr: '2026-04-21 10:21:46',
    status: 'Dispersado',
    cuadrilla: 'Octopus',
    tarjeta: '1318820',
    fotoTableroAntes: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&q=80&w=100',
    kilometrajeAntes: 363046,
    cargaMxn: 900,
    cargaAutorizada: 900,
    comentarios: ''
  },
  {
    id: 'GAS-006',
    tipoSolicitud: 'Normal',
    asignacionUso: 'Unidad móvil',
    solicitante: 'martin.bernal@servnet.mx',
    fechaHr: '2026-05-10 23:09:41',
    status: 'Dispersado',
    cuadrilla: 'SilentFiber',
    tarjeta: '1420602',
    fotoTableroAntes: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&q=80&w=100',
    kilometrajeAntes: 120071,
    cargaMxn: 1500,
    cargaAutorizada: 1500,
    comentarios: 'Carga urgente'
  },
  {
    id: 'GAS-007',
    tipoSolicitud: 'Normal',
    asignacionUso: 'Unidad móvil',
    solicitante: 'enrique.rodriguez@servnet.mx',
    fechaHr: '2026-05-18 09:01:21',
    status: 'Dispersado',
    cuadrilla: 'Kraken',
    tarjeta: '1318818',
    fotoTableroAntes: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&q=80&w=100',
    kilometrajeAntes: 334974,
    cargaMxn: 1000,
    cargaAutorizada: 1000,
    comentarios: ''
  }
];

export const USER_CARDS: Record<string, string> = {
  'erika.fernandez@servnet.mx':     '4146',
  'samantha.escamilla@servnet.mx':  '9295',
  'zuriel.macias@servnet.mx':       '9477',
  'filiberto.altamirano@servnet.mx':'4161',
  'elidan.aguirre@servnet.mx':      '4070',
  'andrea.barrera@servnet.mx':      '9550',
  'marco.garcia@servnet.mx':        '4419',
  'ricardo.hernandez@servnet.mx':   '9287',
  'enrique.rodriguez@servnet.mx':   '4369',
  'gerardo.gomez@servnet.mx':       '4187',
  'luis.hernandez@servnet.mx':      '4195',
  'victor.arredondo@servnet.mx':    '9329',
  'martin.bernal@servnet.mx':       '4435',
  'alfonso.enriquez@servnet.mx':    '4021',
};

export const EXPENSE_TYPES = [
  'Alimentos', 'Hospedaje', 'Transporte', 'Gasolina', 'Casetas',
  'Estacionamiento/pensión', 'Otros', 'Tramite CFE', 'Dadiva',
  'Limpieza oficina', 'Comisión por retiro en cajero',
  'Complemento para Adecuación de POP', 'Papelería e Insumos',
  'Compra de Herramienta', 'Complemento para Instalación de Cliente',
  'Insumos Vehiculares', 'Pago de Servicios a Terceros',
  'Antidoping', 'Certificado médico', 'Complemento para Pop',
  'Car wash', 'Agua purificada', 'Arrastre de grúa',
  'Pago por chequeo de equipo', 'Accesorios camioneta',
  'Complemento para generador eléctrico', 'Complemento para Oficina',
];

export const EXPENSE_TYPE_PREFIXES: Record<string, string> = {
  'Alimentos':                              'ALI',
  'Hospedaje':                              'HOS',
  'Transporte':                             'TRP',
  'Gasolina':                               'GAS',
  'Casetas':                                'CAS',
  'Estacionamiento/pensión':                'EST',
  'Otros':                                  'OTR',
  'Tramite CFE':                            'TCFE',
  'Dadiva':                                 'DAD',
  'Limpieza oficina':                       'LIM',
  'Comisión por retiro en cajero':          'COM',
  'Complemento para Adecuación de POP':    'CPOP',
  'Papelería e Insumos':                    'PAP',
  'Compra de Herramienta':                  'CHE',
  'Complemento para Instalación de Cliente':'CIC',
  'Insumos Vehiculares':                    'INV',
  'Pago de Servicios a Terceros':           'PST',
  'Antidoping':                             'ANT',
  'Certificado médico':                     'CEM',
  'Complemento para Pop':                   'CPP',
  'Car wash':                               'CWA',
  'Agua purificada':                        'AGU',
  'Arrastre de grúa':                       'ARR',
  'Pago por chequeo de equipo':             'PCE',
  'Accesorios camioneta':                   'ACC',
  'Complemento para generador eléctrico':  'CGE',
  'Complemento para Oficina':              'COF',
};

export const AUTHORIZED_BY_LIST = [
  'Erika Fernández Lomas', 'Samantha Escamilla Belman',
  'Fabiola Tzaznan Lovera Ceron', 'Andrés Zuriel Macías Ríos',
  'Mario Cesar Sanchez Reyes', 'Itzel Sureyma Espinosa Diaz',
  'Carlos Alberto Moreno Giles', 'Filiberto Altamirano Aguirre',
  'Elidan Aguirre Ortiz', 'Andrea Barrera Esparza',
  'Marco Antonio Garcia Fragoso', 'Ricardo Hernandez Alcala',
  'Ricardo Javier Diaz Garcia', 'Luis Enrique Rodriguez Aguilera',
  'Gerardo Gomez Zavala', 'Luis Manuel de la Rosa Hernández',
  'Luis Alberto Licona Hernández', 'Luis Arturo Rosas Garcia',
  'Mauricio Rubi Ramírez', 'Irving Uriel Reyes Pérez',
  'Leticia Delgado Jeronimo', 'Ivan Rigoberto Hidalgo Ledesma',
  'Juan Armando Morales Sabino', 'Helen Lizbeth Martinez Mendoza',
  'Alma Jimena Juarez Urbina', 'Jose Arturo Vargas Garcia',
  'Fernando Vicente Luna Reyes', 'Operaciones Master',
  'Miguel Ernesto Garcia Cruz', 'Victor Alejandro Arredondo Rangel',
  'Octavio Arian Moreno Colin', 'Martin Giovanni Bernal Perez',
  'Marcos Ordoñez', 'Patricio Tecnico FO Clot 1',
  'Gustavo Angel Ferrer Becerril', 'Alfonso Enriquez Guerrero',
  'Carlos Alberto Capistran', 'Jorge Sauceda', 'TecnicoMTY',
  'Juan Monter', 'Emmanuel Moctezuma',
  'Mario Alberto Rodriguez Espinosa',
];

export const EXPENSE_STATUS_OPTIONS: import('./types').ExpenseStatus[] = [
  'Solicitado', 'Autorizado', 'Reembolsado', 'Cancelado'
];
export const EXPENSE_VALIDATION_TYPES: import('./types').ExpenseValidationType[] = [
  'Gastos', 'Viáticos'
];

export const MOCK_EXPENSES: import('./types').ExpenseRequest[] = [
  {
    id: 'GAS-001',
    userEmail: 'martin.bernal@servnet.mx',
    tarjeta: '4435',
    team: 'Pre-Sales Management',
    tipoComprobacion: 'Gastos',
    fecha: '2026-05-15T10:00:00.000Z',
    noFactura: 'FAC-1002',
    nombreRazonSocial: 'Home Depot',
    motivo: 'Compra de Herramienta',
    tipo: 'Compra de Herramienta',
    total: 2500.00,
    estatus: 'Solicitado'
  },
  {
    id: 'VIA-001',
    userEmail: 'enrique.rodriguez@servnet.mx',
    tarjeta: '4369',
    team: 'Pre-Sales Management',
    tipoComprobacion: 'Viáticos',
    fecha: '2026-05-16T11:30:00.000Z',
    noFactura: 'FAC-3490',
    nombreRazonSocial: 'Hotel City Express',
    motivo: 'Viaje a Monterrey',
    tipo: 'Hospedaje',
    total: 3500.00,
    estatus: 'Autorizado',
    fechaAutorizacion: '2026-05-17T09:00:00.000Z',
    autorizadoPor: 'Samantha Escamilla Belman'
  },
  {
    id: 'GAS-002',
    userEmail: 'gerardo.gomez@servnet.mx',
    tarjeta: '4187',
    team: 'Pre-Sales Management',
    tipoComprobacion: 'Gastos',
    fecha: '2026-05-17T14:15:00.000Z',
    noFactura: 'FAC-9821',
    nombreRazonSocial: 'Office Depot',
    motivo: 'Papelería e Insumos',
    tipo: 'Papelería e Insumos',
    total: 1250.50,
    estatus: 'Reembolsado',
    fechaAutorizacion: '2026-05-18T10:00:00.000Z',
    autorizadoPor: 'Erika Fernández Lomas'
  },
  {
    id: 'VIA-002',
    userEmail: 'alfonso.enriquez@servnet.mx',
    tarjeta: '4021',
    team: 'Pre-Sales Management',
    tipoComprobacion: 'Viáticos',
    fecha: '2026-05-18T16:45:00.000Z',
    noFactura: 'FAC-2341',
    nombreRazonSocial: 'Restaurante el Cardenal',
    motivo: 'Comida con cliente',
    tipo: 'Alimentos',
    total: 800.00,
    estatus: 'Cancelado'
  },
  {
    id: 'GAS-003',
    userEmail: 'andrea.barrera@servnet.mx',
    tarjeta: '9550',
    team: 'Pre-Sales Management',
    tipoComprobacion: 'Gastos',
    fecha: '2026-05-19T09:20:00.000Z',
    noFactura: 'FAC-1122',
    nombreRazonSocial: 'Autolavado',
    motivo: 'Limpieza de camioneta',
    tipo: 'Car wash',
    total: 150.00,
    estatus: 'Solicitado'
  },
  {
    id: 'VIA-003',
    userEmail: 'ricardo.hernandez@servnet.mx',
    tarjeta: '9287',
    team: 'Pre-Sales Management',
    tipoComprobacion: 'Viáticos',
    fecha: '2026-05-19T10:30:00.000Z',
    noFactura: 'FAC-4455',
    nombreRazonSocial: 'Caminos y Puentes',
    motivo: 'Casetas viaje a QRO',
    tipo: 'Casetas',
    total: 450.00,
    estatus: 'Solicitado'
  },
  {
    id: 'GAS-004',
    userEmail: 'marco.garcia@servnet.mx',
    tarjeta: '4419',
    team: 'Pre-Sales Management',
    tipoComprobacion: 'Gastos',
    fecha: '2026-05-19T11:45:00.000Z',
    noFactura: 'FAC-7766',
    nombreRazonSocial: 'Farmacias del Ahorro',
    motivo: 'Certificado medico',
    tipo: 'Certificado médico',
    total: 200.00,
    estatus: 'Autorizado',
    fechaAutorizacion: '2026-05-19T13:00:00.000Z',
    autorizadoPor: 'Erika Fernández Lomas'
  },
  {
    id: 'VIA-004',
    userEmail: 'luis.hernandez@servnet.mx',
    tarjeta: '4195',
    team: 'Pre-Sales Management',
    tipoComprobacion: 'Viáticos',
    fecha: '2026-05-19T14:00:00.000Z',
    noFactura: 'FAC-8899',
    nombreRazonSocial: 'Estacionamiento Centro',
    motivo: 'Visita pop centro',
    tipo: 'Estacionamiento/pensión',
    total: 100.00,
    estatus: 'Solicitado'
  }
];

export const POPS_DATA: import('./types').PopSite[] = [
  { id:'MTY-002', nombre:'MTY-002-LOMA LARGA', nombreCorto:'Loma Larga', status:'activo', lat:25.655017, lng:-100.326608, region:'MTY', tecnologia:'Fiber Optic / Microwave', responsableN1:'Victor Alejandro Arredondo Ranjel', responsableN2:'Hilario Garcia', cuadrilla:'Dynamo', horarioIngreso:'6-22', tiempoLlegada:'1 hora', requerimientosAcceso:'Ninguno', llaveAcceso:false, baterias:'10 horas', calificacion:'ALTA', contactoArrendador:'8128746802' },
  { id:'MTY-007', nombre:'MTY-007-ESTRADA', nombreCorto:'Estrada', status:'activo', lat:25.673607, lng:-100.4336703, region:'MTY', tecnologia:'Fiber Optic / Microwave', responsableN1:'Victor Alejandro Arredondo Ranjel', responsableN2:'Hilario Garcia', cuadrilla:'Dynamo', horarioIngreso:'', tiempoLlegada:'1 hora', requerimientosAcceso:'Ninguno', llaveAcceso:true, baterias:'8 horas', calificacion:'ALTA', contactoArrendador:'8441736715' },
  { id:'MTY-008', nombre:'MTY-008-TORRE CYTRO', nombreCorto:'Torre Cytro', status:'activo', lat:25.64959, lng:-100.35641, region:'MTY', tecnologia:'Microwave', responsableN1:'Victor Alejandro Arredondo Ranjel', responsableN2:'Hilario Garcia', cuadrilla:'Dynamo', horarioIngreso:'8-18', tiempoLlegada:'1 hora', requerimientosAcceso:'Solicitud acceso NH via Correo', llaveAcceso:false, baterias:'P.E', calificacion:'ALTA', contactoArrendador:'nhnoc@nhsolutions.com.mx' },
  { id:'MTY-009', nombre:'MTY-009-GARCÍA', nombreCorto:'García', status:'activo', lat:25.783029, lng:-100.57705, region:'MTY', tecnologia:'Fiber Optic / Microwave', responsableN1:'Victor Alejandro Arredondo Ranjel', responsableN2:'Hilario Garcia', cuadrilla:'Dynamo', horarioIngreso:'', tiempoLlegada:'1 hora', requerimientosAcceso:'Ninguno', llaveAcceso:true, baterias:'12 horas', calificacion:'ALTA', contactoArrendador:'8111134231' },
  { id:'MTY-003', nombre:'MTY-003-ANODIZE', nombreCorto:'Anodize', status:'activo', lat:25.718919, lng:-100.208433, region:'MTY', tecnologia:'Microwave', responsableN1:'Carlos Alberto Capistran', responsableN2:'Hilario Garcia', cuadrilla:'Megatron', horarioIngreso:'', tiempoLlegada:'1 hora', requerimientosAcceso:'Ninguno', llaveAcceso:false, baterias:'8 horas', calificacion:'ALTA', contactoArrendador:'8112894895' },
  { id:'MTY-004', nombre:'MTY-004-CENTRAL SEMILLERO', nombreCorto:'Central Semillero', status:'activo', lat:25.670527, lng:-100.324855, region:'MTY', tecnologia:'Fiber Optic / Microwave', responsableN1:'Carlos Alberto Capistran', responsableN2:'Hilario Garcia', cuadrilla:'Megatron', horarioIngreso:'', tiempoLlegada:'1 hora', requerimientosAcceso:'Solicitud acceso via llamada o whatsapp', llaveAcceso:true, baterias:'8 horas', calificacion:'ALTA', contactoArrendador:'81 2755 7966' },
  { id:'MTY-005', nombre:'MTY-005-LA ESTANZUELA', nombreCorto:'La Estanzuela / Repetidor Sur', status:'activo', lat:25.582067, lng:-100.232049, region:'MTY', tecnologia:'Microwave', responsableN1:'Carlos Alberto Capistran', responsableN2:'Hilario Garcia', cuadrilla:'Megatron', horarioIngreso:'', tiempoLlegada:'1 hora', requerimientosAcceso:'Ninguno', llaveAcceso:false, baterias:'8 horas', calificacion:'ALTA', contactoArrendador:'8127557966' },
  { id:'EMX-004', nombre:'EMX-004-TOLUCA 3', nombreCorto:'Toluca 3', status:'activo', lat:19.29607, lng:-99.66129, region:'EMX', tecnologia:'Microwave', responsableN1:'Mauricio Mendiola Marcelino', responsableN2:'Supervisor CDMX', cuadrilla:'Eastman', horarioIngreso:'', tiempoLlegada:'', requerimientosAcceso:'', llaveAcceso:false, baterias:'', calificacion:'MEDIA', contactoArrendador:'' },
  { id:'EMX-010', nombre:'EMX-010-ARENILLAS', nombreCorto:'Arenillas', status:'activo', lat:19.44243, lng:-99.32461, region:'EMX', tecnologia:'Microwave', responsableN1:'Mauricio Mendiola Marcelino', responsableN2:'Supervisor CDMX', cuadrilla:'Eastman', horarioIngreso:'9 a 9 pm', tiempoLlegada:'1.5 horas', requerimientosAcceso:'Pedir acceso al arrendador', llaveAcceso:false, baterias:'8 horas', calificacion:'MEDIA', contactoArrendador:'' },
  { id:'EMX-018', nombre:'EMX-018-NAUCALPAN', nombreCorto:'Naucalpan. Contrato 3371', status:'activo', lat:19.46612, lng:-99.2259, region:'EMX', tecnologia:'Microwave', responsableN1:'Martin Giovanni Bernal Perez', responsableN2:'Supervisor CDMX', cuadrilla:'SilentFiber', horarioIngreso:'', tiempoLlegada:'1.5 horas', requerimientosAcceso:'Se requiere solicitar el acceso en sitio con los vigilantes', llaveAcceso:false, baterias:'6 horas', calificacion:'ALTA', contactoArrendador:'' },
  { id:'EMX-019', nombre:'EMX-019-TOLUCA_AERO', nombreCorto:'Toluca_Aero', status:'activo', lat:19.34221, lng:-99.58499, region:'EMX', tecnologia:'Microwave', responsableN1:'Luis Manuel de La Rosa Hernandez', responsableN2:'Supervisor CDMX', cuadrilla:'Raptor', horarioIngreso:'9 a 9 pm', tiempoLlegada:'3 horas', requerimientosAcceso:'Se requiere pedir acceso al arrendador', llaveAcceso:false, baterias:'6 horas', calificacion:'ALTA', contactoArrendador:'' },
  { id:'EMX-022', nombre:'EMX-022-TOLUCA_QST', nombreCorto:'Toluca_QST', status:'activo', lat:19.38216, lng:-99.56879, region:'EMX', tecnologia:'Microwave', responsableN1:'Luis Manuel de La Rosa Hernandez', responsableN2:'Supervisor CDMX', cuadrilla:'Raptor', horarioIngreso:'9 a 6 pm', tiempoLlegada:'4 horas', requerimientosAcceso:'Se requiere solicitar acceso con el arrendador antes de acudir', llaveAcceso:false, baterias:'12 horas', calificacion:'MEDIA', contactoArrendador:'' },
  { id:'EMX-001', nombre:'EMX-001-SIDERAL', nombreCorto:'Sideral', status:'activo', lat:19.53558, lng:-99.16583, region:'EMX', tecnologia:'Microwave', responsableN1:'Mauricio Mendiola Marcelino', responsableN2:'Supervisor CDMX', cuadrilla:'Eastman', horarioIngreso:'9 a 6', tiempoLlegada:'1:30h', requerimientosAcceso:'La camioneta se deja abajo y hay que subir muchos escalones', llaveAcceso:false, baterias:'Baterias de gel', calificacion:'BAJA', contactoArrendador:'' },
  { id:'EMX-002', nombre:'EMX-002-ATIZAPAN', nombreCorto:'Atizapan', status:'activo', lat:19.55599, lng:-99.2288, region:'EMX', tecnologia:'Microwave', responsableN1:'Mauricio Mendiola Marcelino', responsableN2:'Supervisor CDMX', cuadrilla:'Eastman', horarioIngreso:'', tiempoLlegada:'', requerimientosAcceso:'', llaveAcceso:true, baterias:'', calificacion:'MEDIA', contactoArrendador:'' },
  { id:'EMX-005', nombre:'EMX-005-JAHUEYES', nombreCorto:'Jahueyes', status:'activo', lat:19.84515, lng:-99.26902, region:'EMX', tecnologia:'Microwave', responsableN1:'Luis Enrique Rodriguez Aguilera', responsableN2:'Supervisor CDMX', cuadrilla:'Kraken', horarioIngreso:'', tiempoLlegada:'1:00h', requerimientosAcceso:'Comunicarse a tiempo con la arrendadora.', llaveAcceso:false, baterias:'Baterias de gel', calificacion:'MEDIA', contactoArrendador:'' },
  { id:'EMX-007', nombre:'EMX-007-EL ROSAL', nombreCorto:'El Rosal', status:'activo', lat:20.1155, lng:-99.667, region:'EMX', tecnologia:'Microwave', responsableN1:'Jorge Iván Sauceda Gaona', responsableN2:'Marcos Ordoñez', cuadrilla:'Neptuno', horarioIngreso:'', tiempoLlegada:'2.5 horas', requerimientosAcceso:'', llaveAcceso:true, baterias:'10 horas', calificacion:'ALTA', contactoArrendador:'673 127 0626' },
  { id:'EMX-008', nombre:'EMX-008-JILOTEPEC 2', nombreCorto:'Jilotepec 2', status:'activo', lat:19.99403, lng:-99.53347, region:'EMX', tecnologia:'Microwave', responsableN1:'Jorge Iván Sauceda Gaona', responsableN2:'Marcos Ordoñez', cuadrilla:'Neptuno', horarioIngreso:'24/', tiempoLlegada:'2.8 horas', requerimientosAcceso:'', llaveAcceso:false, baterias:'8 horas', calificacion:'MEDIA', contactoArrendador:'554 859 5938' },
  { id:'EMX-009', nombre:'EMX-009-JILOTEPEC', nombreCorto:'Jilotepec', status:'activo', lat:19.9304, lng:-99.5167, region:'EMX', tecnologia:'Microwave', responsableN1:'Jorge Iván Sauceda Gaona', responsableN2:'Marcos Ordoñez', cuadrilla:'Neptuno', horarioIngreso:'', tiempoLlegada:'2.8 horas', requerimientosAcceso:'', llaveAcceso:false, baterias:'8 horas', calificacion:'MEDIA', contactoArrendador:'558 142 3806' },
  { id:'EMX-011', nombre:'EMX-011-TULTEPEC', nombreCorto:'Tultepec', status:'activo', lat:19.70253, lng:-99.10793, region:'EMX', tecnologia:'Microwave', responsableN1:'Jose Octavio Marquez Vazquez', responsableN2:'Supervisor CDMX', cuadrilla:'Octopus', horarioIngreso:'', tiempoLlegada:'1:00h', requerimientosAcceso:'Comunicarse con el arrendador', llaveAcceso:false, baterias:'Bateria de litio', calificacion:'ALTA', contactoArrendador:'' },
  { id:'EMX-012', nombre:'EMX-012-TLALNEMEX', nombreCorto:'Tlalnemex', status:'activo', lat:19.52979, lng:-99.2064, region:'EMX', tecnologia:'Microwave', responsableN1:'Mauricio Mendiola Marcelino', responsableN2:'Supervisor CDMX', cuadrilla:'Eastman', horarioIngreso:'9 a 9 pm', tiempoLlegada:'1.5 horas', requerimientosAcceso:'Pedir acceso al arrendador', llaveAcceso:false, baterias:'24 horas', calificacion:'ALTA', contactoArrendador:'' },
  { id:'EMX-013', nombre:'EMX-013-NICOLAS ROMERO', nombreCorto:'Nicolas Romero', status:'activo', lat:19.63719, lng:-99.33524, region:'EMX', tecnologia:'Fiber Optic / Microwave', responsableN1:'Mauricio Mendiola Marcelino', responsableN2:'Supervisor CDMX', cuadrilla:'Eastman', horarioIngreso:'', tiempoLlegada:'', requerimientosAcceso:'', llaveAcceso:false, baterias:'', calificacion:'MEDIA', contactoArrendador:'' },
  { id:'EMX-014', nombre:'EMX-014-LA QUEBRADA', nombreCorto:'La Quebrada', status:'activo', lat:19.5904524915834, lng:-99.1935196286126, region:'EMX', tecnologia:'Microwave', responsableN1:'Jose Octavio Marquez Vazquez', responsableN2:'Supervisor CDMX', cuadrilla:'Octopus', horarioIngreso:'9 a 9 pm', tiempoLlegada:'', requerimientosAcceso:'Solicitar acceso al arrendador y escalera para subir al techo', llaveAcceso:false, baterias:'Banco de litio', calificacion:'ALTA', contactoArrendador:'' },
  { id:'EMX-015', nombre:'EMX-015-CHICONAUTLA', nombreCorto:'Chiconautla', status:'activo', lat:19.6519659975638, lng:-98.9678342448445, region:'EMX', tecnologia:'Microwave', responsableN1:'Jose Octavio Marquez Vazquez', responsableN2:'Supervisor CDMX', cuadrilla:'Octopus', horarioIngreso:'9 a 6', tiempoLlegada:'1:10h', requerimientosAcceso:'Se requiere pedir la llave al señor Piña y al bajar se debe entregar', llaveAcceso:true, baterias:'Bateria de litio', calificacion:'ALTA', contactoArrendador:'' },
  { id:'EMX-016', nombre:'EMX-016-CHIMALHUACAN', nombreCorto:'Chimalhuacan', status:'activo', lat:19.40787, lng:-98.96725, region:'EMX', tecnologia:'Microwave', responsableN1:'Luis Manuel de La Rosa Hernandez', responsableN2:'Supervisor CDMX', cuadrilla:'Raptor', horarioIngreso:'9 a 5 L-V, S 9-2pm', tiempoLlegada:'2 horas', requerimientosAcceso:'Se requiere informar al arrendador en caso de ingresar fuera del horario', llaveAcceso:true, baterias:'', calificacion:'ALTA', contactoArrendador:'' },
  { id:'EMX-017', nombre:'EMX-017-JOCOTITLAN', nombreCorto:'Jocotitlan', status:'activo', lat:19.73774, lng:-99.76224, region:'EMX', tecnologia:'Microwave', responsableN1:'', responsableN2:'Supervisor CDMX', cuadrilla:'', horarioIngreso:'9 a 6 pm', tiempoLlegada:'5 horas', requerimientosAcceso:'Avisar al guardabosques Arnulfo y Mario para el acceso', llaveAcceso:false, baterias:'6 horas, planta de emergencia', calificacion:'MEDIA', contactoArrendador:'' },
  { id:'EMX-021', nombre:'EMX-021-TEXCOCO', nombreCorto:'Texcoco', status:'activo', lat:19.5187, lng:-98.8074, region:'EMX', tecnologia:'Microwave', responsableN1:'Luis Manuel de La Rosa Hernandez', responsableN2:'Supervisor CDMX', cuadrilla:'Raptor', horarioIngreso:'9 a 6 pm', tiempoLlegada:'3 horas', requerimientosAcceso:'Se requiere solicitar acceso con el arrendador antes de acudir', llaveAcceso:false, baterias:'4 horas', calificacion:'MEDIA', contactoArrendador:'' },
  { id:'EMX-023', nombre:'EMX-023-CUAUTITLAN IZCALLI', nombreCorto:'Cuautitlan Izcalli', status:'activo', lat:19.70039, lng:-99.20193, region:'EMX', tecnologia:'Microwave', responsableN1:'Luis Enrique Rodriguez Aguilera', responsableN2:'Supervisor CDMX', cuadrilla:'Kraken', horarioIngreso:'9 a 6', tiempoLlegada:'1:15h', requerimientosAcceso:'No hay acceso fines de semana, mandar correo con anticipacion, deben ir dos personas', llaveAcceso:false, baterias:'Baterias de gel', calificacion:'MEDIA', contactoArrendador:'' },
  { id:'EMX-024', nombre:'EMX-024-CUATRO VIENTOS (CHALCO)', nombreCorto:'Cuatro Vientos (Chalco)', status:'activo', lat:19.2955, lng:-98.8445, region:'EMX', tecnologia:'Microwave', responsableN1:'Jose Octavio Marquez Vazquez', responsableN2:'Supervisor CDMX', cuadrilla:'Octopus', horarioIngreso:'', tiempoLlegada:'', requerimientosAcceso:'', llaveAcceso:false, baterias:'', calificacion:'MEDIA', contactoArrendador:'' },
  { id:'EMX-025', nombre:'EMX-025-ORION', nombreCorto:'Orion', status:'activo', lat:19.70507, lng:-99.126, region:'EMX', tecnologia:'Microwave', responsableN1:'Luis Enrique Rodriguez Aguilera', responsableN2:'Supervisor CDMX', cuadrilla:'Kraken', horarioIngreso:'', tiempoLlegada:'1:00h', requerimientosAcceso:'Avisar al arrendador antes de acudir.', llaveAcceso:true, baterias:'Banco de litio', calificacion:'ALTA', contactoArrendador:'' },
  { id:'EMX-029', nombre:'EMX-029-TLACOLTEPEC', nombreCorto:'Tlacoltepec', status:'activo', lat:19.229917435229, lng:-99.6724974614909, region:'EMX', tecnologia:'Microwave', responsableN1:'Luis Enrique Rodriguez Aguilera', responsableN2:'Supervisor CDMX', cuadrilla:'Kraken', horarioIngreso:'', tiempoLlegada:'4 horas', requerimientosAcceso:'', llaveAcceso:false, baterias:'', calificacion:'MEDIA', contactoArrendador:'' },
  { id:'CMX-001', nombre:'CMX-001-PRESA FALCON', nombreCorto:'Presa Falcon', status:'activo', lat:19.44415, lng:-99.20526, region:'CMX', tecnologia:'Fiber Optic / Microwave', responsableN1:'Mauricio Mendiola Marcelino', responsableN2:'Supervisor CDMX', cuadrilla:'Eastman', horarioIngreso:'', tiempoLlegada:'2 horas', requerimientosAcceso:'N/A', llaveAcceso:false, baterias:'UPS, Planta de emergencia y bancos de baterias', calificacion:'ALTA', contactoArrendador:'' },
  { id:'CMX-002', nombre:'CMX-002-HERSCHEL', nombreCorto:'Herschel', status:'activo', lat:19.4335224750779, lng:-99.1810226024322, region:'CMX', tecnologia:'Fiber Optic', responsableN1:'Mauricio Mendiola Marcelino', responsableN2:'Supervisor CDMX', cuadrilla:'Eastman', horarioIngreso:'9 A 6 pm', tiempoLlegada:'1.3 horas', requerimientosAcceso:'Pedir acceso al arrendador. Srita Blanca 5545958085 fines de semana, Francisco 5542920116 L-V', llaveAcceso:false, baterias:'24 hrs', calificacion:'ALTA', contactoArrendador:'' },
  { id:'CMX-004', nombre:'CMX-004-TACUBA (PARQUE LIRA)', nombreCorto:'Tacuba (Parque Lira)', status:'activo', lat:19.4104951894863, lng:-99.1918200850242, region:'CMX', tecnologia:'Fiber Optic', responsableN1:'Mauricio Mendiola Marcelino', responsableN2:'Supervisor CDMX', cuadrilla:'Eastman', horarioIngreso:'9 a 9 pm', tiempoLlegada:'1.5 horas', requerimientosAcceso:'Pedir acceso al arrendador', llaveAcceso:false, baterias:'12 horas', calificacion:'ALTA', contactoArrendador:'' },
  { id:'CMX-005', nombre:'CMX-005-AZTECA', nombreCorto:'Azteca', status:'activo', lat:19.31932, lng:-99.16296, region:'CMX', tecnologia:'Fiber Optic', responsableN1:'Ricardo Hernandez Alcala', responsableN2:'Supervisor CDMX', cuadrilla:'Pegaso', horarioIngreso:'9 a 9 pm', tiempoLlegada:'1.5 horas', requerimientosAcceso:'Pedir acceso al arrendador', llaveAcceso:true, baterias:'8 horas', calificacion:'ALTA', contactoArrendador:'' },
  { id:'CMX-008', nombre:'CMX-008-IZAZAGA', nombreCorto:'Izazaga', status:'activo', lat:19.42568, lng:-99.13657, region:'CMX', tecnologia:'Fiber Optic / Microwave', responsableN1:'Martin Giovanni Bernal Perez', responsableN2:'Supervisor CDMX', cuadrilla:'SilentFiber', horarioIngreso:'', tiempoLlegada:'', requerimientosAcceso:'Enviar correo a administracion y llevar el acceso impreso', llaveAcceso:false, baterias:'Bateria de litio', calificacion:'ALTA', contactoArrendador:'' },
  { id:'CMX-009', nombre:'CMX-009-CONSTITUYENTES 3', nombreCorto:'Constituyentes 3', status:'activo', lat:19.4017918344471, lng:-99.206596222582, region:'CMX', tecnologia:'Fiber Optic / Microwave', responsableN1:'Martin Giovanni Bernal Perez', responsableN2:'Supervisor CDMX', cuadrilla:'SilentFiber', horarioIngreso:'', tiempoLlegada:'', requerimientosAcceso:'Pedir acceso al vigilante, el gabinete esta en la azotea', llaveAcceso:false, baterias:'18 horas', calificacion:'ALTA', contactoArrendador:'' },
  { id:'CMX-010', nombre:'CMX-010-SAN RAFAEL', nombreCorto:'San Rafael', status:'cancelado', lat:19.4337533, lng:-99.1601892, region:'CMX', tecnologia:'Microwave', responsableN1:'', responsableN2:'Supervisor CDMX', cuadrilla:'', horarioIngreso:'', tiempoLlegada:'', requerimientosAcceso:'', llaveAcceso:false, baterias:'', calificacion:'', contactoArrendador:'' },
  { id:'CMX-011', nombre:'CMX-011-ARAGÓN-2', nombreCorto:'Aragón-2', status:'activo', lat:19.4818530272585, lng:-99.0738970856351, region:'CMX', tecnologia:'Microwave', responsableN1:'Martin Giovanni Bernal Perez', responsableN2:'Supervisor CDMX', cuadrilla:'SilentFiber', horarioIngreso:'9 a 9 pm', tiempoLlegada:'', requerimientosAcceso:'', llaveAcceso:false, baterias:'', calificacion:'ALTA', contactoArrendador:'' },
  { id:'CMX-012', nombre:'CMX-012-RIO LERMA', nombreCorto:'Rio Lerma', status:'activo', lat:19.4258552337291, lng:-99.1751951900664, region:'CMX', tecnologia:'Microwave', responsableN1:'Martin Giovanni Bernal Perez', responsableN2:'Supervisor CDMX', cuadrilla:'SilentFiber', horarioIngreso:'', tiempoLlegada:'1.5 horas', requerimientosAcceso:'Se requiere pedir acceso al guardia, gabinete en estacionamiento primer piso', llaveAcceso:false, baterias:'24 horas', calificacion:'ALTA', contactoArrendador:'' },
  { id:'CMX-013', nombre:'CMX-013-AJUSCO', nombreCorto:'Ajusco', status:'activo', lat:19.2309024, lng:-99.1758482, region:'CMX', tecnologia:'Microwave', responsableN1:'Ricardo Hernandez Alcala', responsableN2:'Supervisor CDMX', cuadrilla:'Pegaso', horarioIngreso:'9 a 6 pm', tiempoLlegada:'2 horas', requerimientosAcceso:'Se requiere el V.o.B.o de la arrendadora, validarlo antes de acudir', llaveAcceso:false, baterias:'', calificacion:'MEDIA', contactoArrendador:'' },
  { id:'CMX-014', nombre:'CMX-014-ROMA NORTE', nombreCorto:'Roma norte', status:'activo', lat:19.423235, lng:-99.160713, region:'CMX', tecnologia:'Fiber Optic', responsableN1:'Martin Giovanni Bernal Perez', responsableN2:'Supervisor CDMX', cuadrilla:'SilentFiber', horarioIngreso:'', tiempoLlegada:'1:30h', requerimientosAcceso:'Registrarse con el vigilante y pedirle la llave del cuarto de elevadores', llaveAcceso:true, baterias:'24 horas', calificacion:'ALTA', contactoArrendador:'' },
  { id:'CMX-015', nombre:'CMX-015-ARAGÓN-1', nombreCorto:'Aragón-1', status:'activo', lat:19.4524, lng:-99.09673, region:'CMX', tecnologia:'Microwave', responsableN1:'Martin Giovanni Bernal Perez', responsableN2:'Supervisor CDMX', cuadrilla:'SilentFiber', horarioIngreso:'9 a 9 pm', tiempoLlegada:'1.5 horas', requerimientosAcceso:'Se requiere solicitar el acceso con el arrendador antes de la visita', llaveAcceso:false, baterias:'12 horas', calificacion:'ALTA', contactoArrendador:'' },
  { id:'CMX-016', nombre:'CMX-016-AZCAPOTZALCO (VALLEJO)', nombreCorto:'Azcapotzalco (vallejo)', status:'activo', lat:19.4980054069, lng:-99.1583161942007, region:'CMX', tecnologia:'Microwave', responsableN1:'Martin Giovanni Bernal Perez', responsableN2:'Supervisor CDMX', cuadrilla:'SilentFiber', horarioIngreso:'24 horas', tiempoLlegada:'', requerimientosAcceso:'El espacio es propio. Se requieren 2 llaves para la puerta', llaveAcceso:true, baterias:'24 horas', calificacion:'ALTA', contactoArrendador:'' },
  { id:'CMX-018', nombre:'CMX-018-DOWN TOWN', nombreCorto:'Down Town', status:'activo', lat:19.3612237977038, lng:-99.265982188455, region:'CMX', tecnologia:'Fiber Optic', responsableN1:'Ricardo Hernandez Alcala', responsableN2:'Supervisor CDMX', cuadrilla:'Pegaso', horarioIngreso:'9 a 6 pm', tiempoLlegada:'1.5 horas', requerimientosAcceso:'Mandar correo a soporte@komit.mx, mreyes@komit.mx, vramirez@komit.mx con fecha, hora, actividad y personal', llaveAcceso:false, baterias:'8 horas', calificacion:'ALTA', contactoArrendador:'' },
  { id:'CMX-019', nombre:'CMX-019-EDIFICIO CASTELAR', nombreCorto:'Edificio Castelar', status:'activo', lat:19.43048, lng:-99.19912, region:'CMX', tecnologia:'Microwave', responsableN1:'Luis Manuel de La Rosa Hernandez', responsableN2:'Supervisor CDMX', cuadrilla:'Raptor', horarioIngreso:'', tiempoLlegada:'1.5 horas', requerimientosAcceso:'Se requiere pedir acceso a la administradora Maria', llaveAcceso:false, baterias:'16 horas', calificacion:'ALTA', contactoArrendador:'' },
  { id:'CMX-020', nombre:'CMX-020-LA IBERO', nombreCorto:'La Ibero', status:'activo', lat:19.370303451976, lng:-99.2665312333293, region:'CMX', tecnologia:'Fiber Optic', responsableN1:'Luis Manuel de La Rosa Hernandez', responsableN2:'Supervisor CDMX', cuadrilla:'Raptor', horarioIngreso:'9 a 6 pm', tiempoLlegada:'1.5 horas', requerimientosAcceso:'Mandar correo a fideicomisovexmas@gmail.com', llaveAcceso:false, baterias:'8 horas', calificacion:'ALTA', contactoArrendador:'' },
  { id:'CMX-021', nombre:'CMX-021-SANTA MARIA INSURGENTES', nombreCorto:'Santa Maria Insurgentes', status:'activo', lat:19.4584060635631, lng:-99.1494869697784, region:'CMX', tecnologia:'Fiber Optic', responsableN1:'Luis Manuel de La Rosa Hernandez', responsableN2:'Supervisor CDMX', cuadrilla:'Raptor', horarioIngreso:'9 a 9 pm', tiempoLlegada:'1.5 horas', requerimientosAcceso:'Solicitar acceso con el arrendador antes de acudir', llaveAcceso:false, baterias:'4 horas', calificacion:'BAJA', contactoArrendador:'' },
  { id:'CMX-022', nombre:'CMX-022-TORRE LATINO', nombreCorto:'Torre Latino', status:'activo', lat:19.4338604227725, lng:-99.1406291723004, region:'CMX', tecnologia:'Fiber Optic', responsableN1:'Luis Manuel de La Rosa Hernandez', responsableN2:'Supervisor CDMX', cuadrilla:'Raptor', horarioIngreso:'9 a 5 pm', tiempoLlegada:'1.5 horas', requerimientosAcceso:'Solicitar acceso con 24hrs de anticipación: rhernandezo@torrelatino.net, hcruzm@torrelatino.net', llaveAcceso:true, baterias:'6 horas', calificacion:'ALTA', contactoArrendador:'' },
  { id:'CMX-023', nombre:'CMX-023-(LUZ SAVIÑON) NAPOLES', nombreCorto:'(Luz Saviñon) Napoles', status:'cancelado', lat:19.3903962999402, lng:-99.1547987555151, region:'CMX', tecnologia:'Fiber Optic', responsableN1:'', responsableN2:'Supervisor CDMX', cuadrilla:'', horarioIngreso:'', tiempoLlegada:'', requerimientosAcceso:'', llaveAcceso:false, baterias:'', calificacion:'', contactoArrendador:'' },
  { id:'CMX-025', nombre:'CMX-025-NEXTENGO', nombreCorto:'Nextengo', status:'activo', lat:19.4724400479145, lng:-99.1915082237193, region:'CMX', tecnologia:'Fiber Optic', responsableN1:'Jose Octavio Marquez Vazquez', responsableN2:'Supervisor CDMX', cuadrilla:'Octopus', horarioIngreso:'', tiempoLlegada:'1.5 horas', requerimientosAcceso:'Presentar formato de acceso con vigilantes (gestiona Andrea de telefonia)', llaveAcceso:true, baterias:'12 horas', calificacion:'ALTA', contactoArrendador:'' },
  { id:'CMX-026', nombre:'CMX-026-SANTA FE 01', nombreCorto:'Santa Fe 01', status:'activo', lat:19.358237258695, lng:-99.2741905035133, region:'CMX', tecnologia:'Fiber Optic', responsableN1:'Jose Octavio Marquez Vazquez', responsableN2:'Supervisor CDMX', cuadrilla:'Octopus', horarioIngreso:'', tiempoLlegada:'2 horas', requerimientosAcceso:'Solicitar acceso por correo administracion@corpsantafe505.com', llaveAcceso:false, baterias:'8 horas', calificacion:'ALTA', contactoArrendador:'' },
  { id:'CMX-027', nombre:'CMX-027-SANTA FE 02', nombreCorto:'Santa Fe 02', status:'activo', lat:19.3629229538075, lng:-99.2821434148892, region:'CMX', tecnologia:'Fiber Optic', responsableN1:'Jose Octavio Marquez Vazquez', responsableN2:'Supervisor CDMX', cuadrilla:'Octopus', horarioIngreso:'9 a 5 pm', tiempoLlegada:'2 horas', requerimientosAcceso:'Solicitar acceso vía correo', llaveAcceso:false, baterias:'Sin banco de baterias', calificacion:'ALTA', contactoArrendador:'' },
  { id:'CMX-028', nombre:'CMX-028-KIO MEX/2', nombreCorto:'KIO MEX/2', status:'activo', lat:19.3633926, lng:-99.2802199, region:'CMX', tecnologia:'Fiber Optic', responsableN1:'Jose Octavio Marquez Vazquez', responsableN2:'Supervisor CDMX', cuadrilla:'Octopus', horarioIngreso:'', tiempoLlegada:'', requerimientosAcceso:'', llaveAcceso:false, baterias:'', calificacion:'', contactoArrendador:'' },
  { id:'CMX-030', nombre:'CMX-030-SAN JUAN-DATACENTER', nombreCorto:'San Juan-Datacenter', status:'activo', lat:19.4291408221344, lng:-99.1443246286151, region:'CMX', tecnologia:'Fiber Optic', responsableN1:'Jose Octavio Marquez Vazquez', responsableN2:'Supervisor CDMX', cuadrilla:'Octopus', horarioIngreso:'', tiempoLlegada:'2 horas', requerimientosAcceso:'Presentar formato de acceso con vigilantes (gestiona Andrea)', llaveAcceso:true, baterias:'8 horas', calificacion:'ALTA', contactoArrendador:'' },
  { id:'CMX-032', nombre:'CMX-032-CIRION', nombreCorto:'Cirion', status:'activo', lat:19.441873589165, lng:-99.2024300161016, region:'CMX', tecnologia:'Microwave', responsableN1:'Luis Enrique Rodriguez Aguilera', responsableN2:'Supervisor CDMX', cuadrilla:'Kraken', horarioIngreso:'', tiempoLlegada:'2 horas', requerimientosAcceso:'Solicitar acceso via correo docmexico@ciriontechnologies.com con formato específico', llaveAcceso:false, baterias:'Sin banco de baterias (data center)', calificacion:'MEDIA', contactoArrendador:'' },
  { id:'CMX-033', nombre:'CMX-033-SAN RAFAEL', nombreCorto:'San Rafael', status:'activo', lat:19.4391436189135, lng:-99.1618988605316, region:'CMX', tecnologia:'Microwave', responsableN1:'Martin Giovanni Bernal Perez', responsableN2:'Supervisor CDMX', cuadrilla:'SilentFiber', horarioIngreso:'', tiempoLlegada:'', requerimientosAcceso:'Espacio privado. Llave para puerta principal y 3 llaves para cuarto de servicio', llaveAcceso:true, baterias:'12 horas', calificacion:'MEDIA', contactoArrendador:'' },
  { id:'CMX-034', nombre:'CMX-034-(LUZ SAVIÑON) NARVARTE', nombreCorto:'(Luz Saviñon) Narvarte', status:'activo', lat:19.3920662, lng:-99.1491069, region:'CMX', tecnologia:'Fiber Optic', responsableN1:'Luis Manuel de La Rosa Hernandez', responsableN2:'Supervisor CDMX', cuadrilla:'Raptor', horarioIngreso:'', tiempoLlegada:'1.5 horas', requerimientosAcceso:'Avisar al arrendador para acceso nocturno. Se requiere llave del gabinete', llaveAcceso:true, baterias:'12 horas', calificacion:'ALTA', contactoArrendador:'' },
  { id:'QRO-001', nombre:'QRO-001-BUENAVISTA QRO.', nombreCorto:'Buenavista Qro.', status:'activo', lat:20.328945, lng:-100.027911, region:'QRO', tecnologia:'Microwave', responsableN1:'Jorge Iván Sauceda Gaona', responsableN2:'Marcos Ordoñez', cuadrilla:'Neptuno', horarioIngreso:'', tiempoLlegada:'2 horas', requerimientosAcceso:'', llaveAcceso:false, baterias:'15 horas', calificacion:'ALTA', contactoArrendador:'Magali 427 158 6529' },
  { id:'QRO-002', nombre:'QRO-002-QUERETARO 1', nombreCorto:'Queretaro 1', status:'activo', lat:20.6655806738837, lng:-100.374223, region:'QRO', tecnologia:'Microwave', responsableN1:'Jorge Iván Sauceda Gaona', responsableN2:'Marcos Ordoñez', cuadrilla:'Neptuno', horarioIngreso:'', tiempoLlegada:'1.3 horas', requerimientosAcceso:'', llaveAcceso:true, baterias:'12 horas', calificacion:'ALTA', contactoArrendador:'' },
  { id:'QRO-003', nombre:'QRO-003-CASA BLANCA QRO.', nombreCorto:'Casa Blanca Qro.', status:'activo', lat:20.5066535654504, lng:-100.1707774, region:'QRO', tecnologia:'Microwave', responsableN1:'Jorge Iván Sauceda Gaona', responsableN2:'Marcos Ordoñez', cuadrilla:'Neptuno', horarioIngreso:'', tiempoLlegada:'1 hora', requerimientosAcceso:'', llaveAcceso:false, baterias:'10 horas', calificacion:'MEDIA', contactoArrendador:'442 775 2823' },
  { id:'QRO-004', nombre:'QRO-004-CHROMAFLO', nombreCorto:'Chromaflo', status:'activo', lat:20.5730327293479, lng:-100.264474908317, region:'QRO', tecnologia:'Microwave', responsableN1:'Jorge Iván Sauceda Gaona', responsableN2:'Marcos Ordoñez', cuadrilla:'Neptuno', horarioIngreso:'', tiempoLlegada:'1.6 horas', requerimientosAcceso:'', llaveAcceso:true, baterias:'10 horas', calificacion:'ALTA', contactoArrendador:'ING. Alan 554 828 6144' },
  { id:'QRO-005', nombre:'QRO-005-QUERETARO 2', nombreCorto:'Queretaro 2', status:'activo', lat:20.5573539585015, lng:-100.375628128835, region:'QRO', tecnologia:'Microwave', responsableN1:'Jorge Iván Sauceda Gaona', responsableN2:'Marcos Ordoñez', cuadrilla:'Neptuno', horarioIngreso:'9am / 7pm', tiempoLlegada:'1.5 horas', requerimientosAcceso:'', llaveAcceso:false, baterias:'8 horas', calificacion:'MEDIA', contactoArrendador:'Flabio Meliton 442 136 2278' },
  { id:'QRO-006', nombre:'QRO-006-CONNIN', nombreCorto:'Connin', status:'activo', lat:20.5799636048269, lng:-100.323655192947, region:'QRO', tecnologia:'Microwave', responsableN1:'Jorge Iván Sauceda Gaona', responsableN2:'Marcos Ordoñez', cuadrilla:'Neptuno', horarioIngreso:'', tiempoLlegada:'1.7 horas', requerimientosAcceso:'', llaveAcceso:false, baterias:'NA', calificacion:'BAJA', contactoArrendador:'Sr. Ricardo 442 502 2356' },
  { id:'QRO-007', nombre:'QRO-007-LOMA DEL CHINO', nombreCorto:'Loma del Chino', status:'activo', lat:20.848667, lng:-100.477598, region:'QRO', tecnologia:'Microwave', responsableN1:'Jorge Iván Sauceda Gaona', responsableN2:'Marcos Ordoñez', cuadrilla:'Neptuno', horarioIngreso:'', tiempoLlegada:'1.4 horas', requerimientosAcceso:'', llaveAcceso:false, baterias:'10 horas', calificacion:'MEDIA', contactoArrendador:'Sr. Roberto 442 680 8633' },
  { id:'QRO-008', nombre:'QRO-008-EQUINIX', nombreCorto:'Equinix', status:'activo', lat:20.5579415455904, lng:-100.278810110903, region:'QRO', tecnologia:'Fiber Optic', responsableN1:'Jorge Iván Sauceda Gaona', responsableN2:'Marcos Ordoñez', cuadrilla:'Neptuno', horarioIngreso:'', tiempoLlegada:'1.3 horas', requerimientosAcceso:'', llaveAcceso:true, baterias:'', calificacion:'ALTA', contactoArrendador:'' },
  { id:'HID-001', nombre:'HID-001-OLMOS', nombreCorto:'Olmos', status:'activo', lat:19.88083, lng:-98.92542, region:'HID', tecnologia:'Microwave', responsableN1:'Luis Enrique Rodriguez Aguilera', responsableN2:'Supervisor CDMX', cuadrilla:'Kraken', horarioIngreso:'', tiempoLlegada:'0:40m', requerimientosAcceso:'Comunicarse con la arrendadora', llaveAcceso:false, baterias:'Baterias de litio', calificacion:'MEDIA', contactoArrendador:'' },
  { id:'HID-002', nombre:'HID-002-TULA', nombreCorto:'Tula', status:'activo', lat:19.97308, lng:-99.24265, region:'HID', tecnologia:'Microwave', responsableN1:'Luis Enrique Rodriguez Aguilera', responsableN2:'Supervisor CDMX', cuadrilla:'Kraken', horarioIngreso:'', tiempoLlegada:'1:00h', requerimientosAcceso:'Contactar el arrendador avisar un dia antes', llaveAcceso:false, baterias:'Baterias de gel', calificacion:'MEDIA', contactoArrendador:'' },
  { id:'HID-003', nombre:'HID-003-QUMA', nombreCorto:'QUMA', status:'activo', lat:19.9004, lng:-99.2184, region:'HID', tecnologia:'Fiber Optic / Microwave', responsableN1:'Luis Enrique Rodriguez Aguilera', responsableN2:'Supervisor CDMX', cuadrilla:'Kraken', horarioIngreso:'', tiempoLlegada:'1:00h', requerimientosAcceso:'Comunicarse con el arrendador, se requiere llave para ingreso al edificio.', llaveAcceso:true, baterias:'Baterias de gel, pendiente cambio a litio', calificacion:'BAJA', contactoArrendador:'' },
  { id:'HID-004', nombre:'HID-004-TEPEAPULCO', nombreCorto:'Tepeapulco', status:'activo', lat:19.7636308162123, lng:-98.5289527707497, region:'HID', tecnologia:'Microwave', responsableN1:'Luis Enrique Rodriguez Aguilera', responsableN2:'Supervisor CDMX', cuadrilla:'Kraken', horarioIngreso:'9 a 6 pm', tiempoLlegada:'1:45h', requerimientosAcceso:'Recoger llave con el arrendador antes de acudir, llamar con anticipacion.', llaveAcceso:true, baterias:'Banco de litio', calificacion:'ALTA', contactoArrendador:'' },
  { id:'MOR-001', nombre:'MOR-001-CUERNAVACA 3', nombreCorto:'Cuernavaca 3', status:'activo', lat:18.8893, lng:-99.1178, region:'MOR', tecnologia:'Microwave', responsableN1:'Ricardo Hernandez Alcala', responsableN2:'Supervisor CDMX', cuadrilla:'Pegaso', horarioIngreso:'', tiempoLlegada:'', requerimientosAcceso:'', llaveAcceso:true, baterias:'', calificacion:'ALTA', contactoArrendador:'' },
  { id:'MOR-002', nombre:'MOR-002-CUERNAVACA 1', nombreCorto:'Cuernavaca 1', status:'activo', lat:18.8799, lng:-99.13322, region:'MOR', tecnologia:'Microwave', responsableN1:'Ricardo Hernandez Alcala', responsableN2:'Supervisor CDMX', cuadrilla:'Pegaso', horarioIngreso:'', tiempoLlegada:'', requerimientosAcceso:'', llaveAcceso:false, baterias:'', calificacion:'BAJA', contactoArrendador:'' },
  { id:'MOR-003', nombre:'MOR-003-CUERNAVACA 4', nombreCorto:'Cuernavaca 4', status:'activo', lat:18.86975, lng:-99.14598, region:'MOR', tecnologia:'Microwave', responsableN1:'Ricardo Hernandez Alcala', responsableN2:'Supervisor CDMX', cuadrilla:'Pegaso', horarioIngreso:'', tiempoLlegada:'', requerimientosAcceso:'', llaveAcceso:false, baterias:'', calificacion:'ALTA', contactoArrendador:'' },
  { id:'MOR-004', nombre:'MOR-004-CUERNAVACA 2', nombreCorto:'Cuernavaca 2', status:'cancelado', lat:18.9255, lng:-99.2154, region:'MOR', tecnologia:'Microwave', responsableN1:'', responsableN2:'Supervisor CDMX', cuadrilla:'Pegaso', horarioIngreso:'9 a 6 pm', tiempoLlegada:'4 horas', requerimientosAcceso:'Avisar al vigilante, se requiere la llave del gabinete', llaveAcceso:true, baterias:'24 horas', calificacion:'ALTA', contactoArrendador:'' },
  { id:'MOR-005', nombre:'MOR-005-CUERNAVACA 5', nombreCorto:'Cuernavaca 5', status:'cancelado', lat:18.85369, lng:-99.18364, region:'MOR', tecnologia:'Microwave', responsableN1:'', responsableN2:'Supervisor CDMX', cuadrilla:'', horarioIngreso:'', tiempoLlegada:'', requerimientosAcceso:'', llaveAcceso:false, baterias:'', calificacion:'MEDIA', contactoArrendador:'' },
  { id:'MOR-006', nombre:'MOR-006-CUERNAVACA 2', nombreCorto:'Cuernavaca 2', status:'activo', lat:18.9255, lng:-99.2154, region:'MOR', tecnologia:'Microwave', responsableN1:'Ricardo Hernandez Alcala', responsableN2:'Supervisor CDMX', cuadrilla:'Pegaso', horarioIngreso:'9 a 6 pm', tiempoLlegada:'4 horas', requerimientosAcceso:'Avisar al vigilante, se requiere la llave del gabinete', llaveAcceso:true, baterias:'24 horas', calificacion:'ALTA', contactoArrendador:'' },
  { id:'PUE-001', nombre:'PUE-001-PUEBLA', nombreCorto:'Puebla', status:'activo', lat:19.04235, lng:-98.18103, region:'PUE', tecnologia:'Microwave', responsableN1:'Ricardo Hernandez Alcala', responsableN2:'Supervisor CDMX', cuadrilla:'Pegaso', horarioIngreso:'', tiempoLlegada:'', requerimientosAcceso:'', llaveAcceso:true, baterias:'', calificacion:'ALTA', contactoArrendador:'' },
  { id:'PUE-002', nombre:'PUE-002-ATLIXCO', nombreCorto:'Atlixco', status:'activo', lat:18.96471, lng:-98.34496, region:'PUE', tecnologia:'Microwave', responsableN1:'Ricardo Hernandez Alcala', responsableN2:'Supervisor CDMX', cuadrilla:'Pegaso', horarioIngreso:'', tiempoLlegada:'3 horas', requerimientosAcceso:'Se requieren 4 llaves para acceder', llaveAcceso:true, baterias:'24 horas', calificacion:'MEDIA', contactoArrendador:'' },
  { id:'GDL-001', nombre:'GDL-001-GUADALAJARA', nombreCorto:'Guadalajara', status:'activo', lat:20.65642, lng:-103.35751, region:'GDL', tecnologia:'Microwave', responsableN1:'Jorge Iván Sauceda Gaona', responsableN2:'Marcos Ordoñez', cuadrilla:'Neptuno', horarioIngreso:'', tiempoLlegada:'5 horas', requerimientosAcceso:'', llaveAcceso:true, baterias:'10 horas', calificacion:'MEDIA', contactoArrendador:'331 005 9133' },
  { id:'GDL-002', nombre:'GDL-002-GUADALAJARA 1', nombreCorto:'Guadalajara 1', status:'activo', lat:20.60079, lng:-103.35412, region:'GDL', tecnologia:'Microwave', responsableN1:'Jorge Iván Sauceda Gaona', responsableN2:'Marcos Ordoñez', cuadrilla:'Neptuno', horarioIngreso:'', tiempoLlegada:'5 horas', requerimientosAcceso:'', llaveAcceso:true, baterias:'10 horas', calificacion:'MEDIA', contactoArrendador:'331 410 4973' },
];

export const MOCK_OVERTIME_RECORDS: import('./types').OvertimeRecord[] = [
  { id: 'CHK-001', email: 'carlos.capistran@servnet.mx', cuadrilla: 'Megatron', checkInLocation: { lat: 25.6705, lng: -100.3248 }, timeCheckIn: '2023-11-20T08:00:00', timeCheckOut: '2023-11-20T21:00:00', horasRegistradas: 13, horasExtrasCalculadas: 4, date: '20/11/2023', status: 'Pagado', horasAutorizadas: 4, semanaRegistro: '47', semanaPago: '48', metodoPago: 'Nómina', comentarios: 'Servicio en Semillero' },
  { id: 'CHK-002', email: 'victor.arredondo@servnet.mx', cuadrilla: 'Dynamo', checkInLocation: { lat: 25.6550, lng: -100.3266 }, timeCheckIn: '2023-11-21T07:00:00', timeCheckOut: '2023-11-21T19:30:00', horasRegistradas: 12.5, horasExtrasCalculadas: 3.5, date: '21/11/2023', status: 'Pagado', horasAutorizadas: 3.5, semanaRegistro: '47', semanaPago: '48', metodoPago: 'Nómina', comentarios: 'Mantenimiento' },
  { id: 'CHK-003', email: 'mauricio.mendiola@servnet.mx', cuadrilla: 'Eastman', checkInLocation: { lat: 19.4441, lng: -99.2052 }, timeCheckIn: '2023-11-22T09:00:00', timeCheckOut: '2023-11-22T20:00:00', horasRegistradas: 11, horasExtrasCalculadas: 2, date: '22/11/2023', status: 'Autorizado', horasAutorizadas: 2, semanaRegistro: '47', semanaPago: '', metodoPago: '', comentarios: 'Atención correctiva' },
  { id: 'CHK-004', email: 'ricardo.alcala@servnet.mx', cuadrilla: 'Pegaso', checkInLocation: { lat: 19.3193, lng: -99.1629 }, timeCheckIn: '2023-11-23T08:00:00', timeCheckOut: '2023-11-23T20:30:00', horasRegistradas: 12.5, horasExtrasCalculadas: 3.5, date: '23/11/2023', status: 'Autorizado', horasAutorizadas: 3, semanaRegistro: '47', semanaPago: '', metodoPago: '', comentarios: 'Instalación nueva' },
  { id: 'CHK-005', email: 'jorge.sauceda@servnet.mx', cuadrilla: 'Neptuno', checkInLocation: { lat: 20.3289, lng: -100.0279 }, timeCheckIn: '2023-11-24T06:00:00', timeCheckOut: '2023-11-24T18:00:00', horasRegistradas: 12, horasExtrasCalculadas: 3, date: '24/11/2023', status: 'En revisión', horasAutorizadas: 0, semanaRegistro: '47', semanaPago: '', metodoPago: '', comentarios: 'Revisión Querétaro' },
  { id: 'CHK-006', email: 'luis.rodriguez@servnet.mx', cuadrilla: 'Kraken', checkInLocation: { lat: 19.8808, lng: -98.9254 }, timeCheckIn: '2023-11-25T08:30:00', timeCheckOut: '2023-11-25T19:30:00', horasRegistradas: 11, horasExtrasCalculadas: 2, date: '25/11/2023', status: 'En revisión', horasAutorizadas: 0, semanaRegistro: '47', semanaPago: '', metodoPago: '', comentarios: 'Visita Olmos' },
  { id: 'CHK-007', email: 'martin.bernal@servnet.mx', cuadrilla: 'SilentFiber', checkInLocation: { lat: 19.4661, lng: -99.2259 }, timeCheckIn: '2023-11-26T07:00:00', timeCheckOut: '2023-11-26T18:00:00', horasRegistradas: 11, horasExtrasCalculadas: 2, date: '26/11/2023', status: 'En revisión', horasAutorizadas: 0, semanaRegistro: '48', semanaPago: '', metodoPago: '', comentarios: 'Guardia fin de semana' },
  { id: 'CHK-008', email: 'jose.marquez@servnet.mx', cuadrilla: 'Octopus', checkInLocation: { lat: 19.5904, lng: -99.1935 }, timeCheckIn: '2023-11-27T08:00:00', timeCheckOut: '2023-11-27T19:00:00', horasRegistradas: 11, horasExtrasCalculadas: 2, date: '27/11/2023', status: 'En revisión', horasAutorizadas: 0, semanaRegistro: '48', semanaPago: '', metodoPago: '', comentarios: 'Atención La Quebrada' },
  { id: 'CHK-009', email: 'luis.delarosa@servnet.mx', cuadrilla: 'Raptor', checkInLocation: { lat: 19.4304, lng: -99.1991 }, timeCheckIn: '2023-11-27T03:00:00', timeCheckOut: '2023-11-27T15:00:00', horasRegistradas: 12, horasExtrasCalculadas: 6, date: '27/11/2023', status: 'En revisión', horasAutorizadas: 0, semanaRegistro: '48', semanaPago: '', metodoPago: '', comentarios: 'Edificio Castelar' },
  { id: 'CHK-010', email: 'victor.arredondo@servnet.mx', cuadrilla: 'Dynamo', checkInLocation: { lat: 25.6495, lng: -100.3564 }, timeCheckIn: '2023-11-28T08:00:00', timeCheckOut: '2023-11-28T18:30:00', horasRegistradas: 10.5, horasExtrasCalculadas: 1.5, date: '28/11/2023', status: 'En revisión', horasAutorizadas: 0, semanaRegistro: '48', semanaPago: '', metodoPago: '', comentarios: 'Torre Cytro' }
];

