import { NavItem, User, CheckRequest, CheckStatus, Service, GasRequest } from './types';

export const USER_DIRECTORY: User[] = [
  { email: 'luis.hernandez@servnet.mx',     region: 'CMX', alias: 'Raptor',     nombre: 'Luis Manuel de la Rosa Hernandez',      rol: 'CUADRILLA' },
  { email: 'victor.arredondo@servnet.mx',   region: 'MTY', alias: 'Dynamo',     nombre: 'Victor Alejandro Arredondo Rangel',     rol: 'CUADRILLA' },
  { email: 'carlos.capistran@servnet.mx',   region: 'MTY', alias: 'Megatron',   nombre: 'Carlos Alberto Capistran Ortega',       rol: 'CUADRILLA' },
  { email: 'martin.bernal@servnet.mx',      region: 'CMX', alias: 'SilentFiber',nombre: 'Martin Giovanni Bernal Perez',          rol: 'CUADRILLA' },
  { email: 'enrique.rodriguez@servnet.mx',  region: 'CMX', alias: 'Kraken',     nombre: 'Luis Enrique Rodriguez Aguilera',       rol: 'CUADRILLA' },
  { email: 'ricardo.hernandez@servnet.mx',  region: 'CMX', alias: 'Pegaso',     nombre: 'Ricardo Hernandez Alcala',              rol: 'CUADRILLA' },
  { email: 'jorge.sauceda@servnet.mx',      region: 'QRO', alias: 'Neptuno',    nombre: 'Jorge Ivan Sauceda Gaona',              rol: 'CUADRILLA' },
  { email: 'mauricio.mendiola@servnet.mx',  region: 'CMX', alias: 'Eastman',    nombre: 'Mauricio Mendiola Marcelino',           rol: 'CUADRILLA' },
  { email: 'octavio.marquez@servnet.mx',    region: 'CMX', alias: 'Octopus',    nombre: 'José Octavio Márquez Vazquez',          rol: 'CUADRILLA' },
];

export const NAV_ITEMS: NavItem[] = [
  { id: 'mis-asignaciones', label: 'Mis Asignaciones' },
  { id: 'check-in-out', label: 'Check In/Out' },
  { id: 'servicios', label: 'Servicios' },
  { id: 'solicitud-gasolina', label: 'Solicitud de Gasolina' },
  { id: 'comprobacion-gastos', label: 'Comprobación de Gastos' },
  { id: 'gestion-horas-extras', label: 'Gestión de Horas Extras' },
  { id: 'gestion-cuadrillas', label: 'Gestión de Cuadrillas' },
  { id: 'ubicacion-pops', label: 'Ubicación de PoPs' },
  { id: 'cierre-empalme', label: 'Cierre de Empalme' },
  { id: 'sla', label: 'SLA' }
];

export const CHECK_STATUS_OPTIONS: CheckStatus[] = ['En revisión', 'Autorizado', 'Rechazado', 'Pagado'];

export const SQUAD_ALIASES = [
  'Nemo', 'Raptor', 'SilentFiber', 'Pegaso', 'Barracuda', 'Phoenix',
  'Octopus', 'Dynamo', 'Megatron', 'Kraken', 'Poseidón', 'Neptuno',
  'Eastman', 'Fibonacci', 'PacketLoss', 'Jitter', 'Optimus', 'Britmor'
];

export const MOCK_CHECKS: CheckRequest[] = [
  {
    id: '88317557',
    email: 'ricardo.hernandez@servnet.mx',
    cuadrilla: 'Pegaso',
    timeCheckIn: '2026-05-11T06:31:36',
    timeCheckOut: '2026-05-11T18:12:53',
    checkInLocation: { lat: 19.444045, lng: -99.204560 },
    checkOutLocation: { lat: 19.444245, lng: -99.204660 },
    status: 'En revisión',
    horasAutorizadas: 0,
    comentarios: ''
  },
  {
    id: '2bf6aadd',
    email: 'luis.hernandez@servnet.mx',
    cuadrilla: 'Raptor',
    timeCheckIn: '2026-05-11T07:45:37',
    timeCheckOut: '2026-05-11T16:30:00',
    checkInLocation: { lat: 19.432608, lng: -99.133209 },
    status: 'Autorizado',
    horasAutorizadas: 8.5,
    comentarios: 'Todo en orden'
  },
  {
    id: 'fe4aabef',
    email: 'octavio.marquez@servnet.mx',
    cuadrilla: 'Octopus',
    timeCheckIn: '2026-05-11T07:54:09',
    checkInLocation: { lat: 19.400000, lng: -99.150000 },
    status: 'En revisión',
    horasAutorizadas: 0,
    comentarios: ''
  },
  {
    id: 'b1a44830',
    email: 'martin.bernal@servnet.mx',
    cuadrilla: 'SilentFiber',
    timeCheckIn: '2026-05-11T08:05:23',
    checkInLocation: { lat: 19.350000, lng: -99.200000 },
    status: 'En revisión',
    horasAutorizadas: 0,
    comentarios: ''
  },
  {
    id: '733ba963',
    email: 'victor.arredondo@servnet.mx',
    cuadrilla: 'Dynamo',
    timeCheckIn: '2026-05-11T08:21:37',
    checkInLocation: { lat: 25.6866, lng: -100.3161 },
    status: 'En revisión',
    horasAutorizadas: 0,
    comentarios: ''
  },
  {
    id: '1b107b9e',
    email: 'jorge.sauceda@servnet.mx',
    cuadrilla: 'Neptuno',
    timeCheckIn: '2026-10-05T06:06:54',
    timeCheckOut: '2026-10-05T16:03:09',
    checkInLocation: { lat: 20.6139, lng: -100.3886 },
    status: 'Pagado',
    horasAutorizadas: 10,
    comentarios: 'Pago quincena 1'
  },
  {
    id: 'ef696cad',
    email: 'mauricio.mendiola@servnet.mx',
    cuadrilla: 'Eastman',
    timeCheckIn: '2026-05-09T09:41:27',
    timeCheckOut: '2026-05-09T17:49:49',
    checkInLocation: { lat: 19.4326, lng: -99.1332 },
    status: 'Autorizado',
    horasAutorizadas: 8,
    comentarios: ''
  },
  {
    id: 'd569fdc5',
    email: 'mauricio.mendiola@servnet.mx',
    cuadrilla: 'Eastman',
    timeCheckIn: '2026-08-05T07:14:50',
    timeCheckOut: '2026-08-05T21:40:12',
    checkInLocation: { lat: 19.4326, lng: -99.1332 },
    status: 'En revisión',
    horasAutorizadas: 0,
    comentarios: ''
  }
];

export const CATEGORY_PREFIXES: Record<string, string> = {
  'Factibilidad en sitio': 'SS',
  'Scouting': 'SCOUT',
  'Ingreso de vehiculo al taller': 'INGVT',
  'Ingenieria de cierre y continuidad': 'IC',
  'Abasto de materiales': 'ABM',
  'Auditoria de cuadrillas': 'AUDC',
  'Trabajo de escritorio': 'TE',
  'Capacitación': 'CAP',
  'Recolección de equipos': 'RE',
  'Actividad en Guardia': 'GUA',
  'Apoyo general a otras áreas': 'AGOA',
  'Auditoria de Pop': 'AUDPOP',
  'Falla CFE en POP': 'FCFE',
  'Servicio fuera de tiempo': 'SFT',
  'Incidencia menor': 'INC',   'Incidencia mayor': 'INC',
  'Mantenimiento menor en Pop': 'MPOP', 'Mantenimiento mayor en Pop': 'MPOP',
  'Instalación menor': 'INST', 'Instalación mayor': 'INST',
  'Mantenimiento menor de rutas fibra': 'MRF',
  'Mantenimiento mayor de rutas fibra': 'MRF',
  'Desinstalación de equipos o cableado menor': 'DESINST',
  'Desinstalación de equipos o cableado mayor': 'DESINST',
  'Upgrade menor': 'UPG', 'Upgrade mayor': 'UPG',
  'Ventana de mantenimiento Cliente menor': 'VMC',
  'Ventana de mantenimiento Cliente mayor': 'VMC',
  'Cambio de domicilio menor': 'CAMD',
  'Cambio de domicilio mayor': 'CAMD',
};

export const CATEGORY_POINTS: Record<string, number> = {
  'Abasto de materiales': 1, 'Recolección de equipos': 1,
  'Incidencia menor': 1, 'Mantenimiento menor en Pop': 1,
  'Instalación menor': 1, 'Ingenieria de cierre y continuidad': 1,
  'Auditoria de cuadrillas': 1, 'Trabajo de escritorio': 1,
  'Capacitación': 1, 'Mantenimiento menor de rutas fibra': 1,
  'Desinstalación de equipos o cableado menor': 1,
  'Auditoria de Pop': 1, 'Upgrade menor': 1,
  'Ingreso de vehiculo al taller': 1, 'Cambio de domicilio menor': 1,
  'Apoyo general a otras áreas': 1, 'Factibilidad en sitio': 2,
  'Scouting': 2, 'Instalación mayor': 2, 'Mantenimiento mayor en Pop': 2,
  'Mantenimiento mayor de rutas fibra': 2,
  'Desinstalación de equipos o cableado mayor': 2,
  'Upgrade mayor': 2, 'Ventana de mantenimiento Cliente menor': 2,
  'Ventana de mantenimiento Cliente mayor': 2,
  'Cambio de domicilio mayor': 2, 'Ventana de mantenimiento menor en POP': 2,
  'Incidencia mayor': 3, 'Falla CFE en POP': 3,
  'Ventana de mantenimiento mayor en POP': 5, 'Actividad en Guardia': 5,
};

export const POPS_LIST = [
  'MTY-002-LOMA LARGA','MTY-007-ESTRADA','MTY-008-TORRE CYTRO',
  'MTY-009-GARCÍA','EMX-004-TOLUCA 3','EMX-010-ARENILLAS',
  'EMX-018-NAUCALPAN','EMX-019-TOLUCA_AERO','CMX-020-LA IBERO',
  'EMX-022-TOLUCA_QST','CMX-025-NEXTENGO','CMX-026-SANTA FE 01',
  'CMX-032-CIRION','EMX-005-JAHUEYES','EMX-023-CUAUTITLAN IZCALLI',
  'EMX-025-ORION','CMX-027-SANTA FE 02','EMX-013-NICOLAS ROMERO',
  'CMX-028-KIO MEX/2','EMX-029-TLACOLTEPEC','HID-001-OLMOS',
  'HID-002-TULA','MTY-003-ANODIZE','MTY-004-CENTRAL SEMILLERO',
  'MTY-005-LA ESTANZUELA','QRO-001-BUENAVISTA','QRO-002-QUERETARO 1',
  'EMX-007-EL ROSAL','EMX-008-JILOTEPEC 2','GDL-001-GUADALAJARA',
  'GDL-002-GUADALAJARA 1','EMX-009-JILOTEPEC','QRO-003-CASA BLANCA',
  'QRO-004-CHROMAFLO','QRO-005-QUERETARO 2','QRO-006-CONNIN',
  'QRO-007-LOMA DEL CHINO','QRO-008-EQUINIX','EMX-001-SIDERAL',
  'EMX-002-ATIZAPAN','PUE-001-PUEBLA','EMX-012-TLALNEMEX',
  'CMX-030-SAN JUAN-DATACENTER','CMX-016-AZCAPOTZALCO',
  'EMX-021-TEXCOCO','HID-003-QUMA','EMX-011-TULTEPEC',
  'MOR-001-CUERNAVACA 3','MOR-002-CUERNAVACA 1','MOR-003-CUERNAVACA 4',
  'CMX-005-AZTECA','PUE-002-ATLIXCO','CMX-013-AJUSCO',
  'EMX-014-LA QUEBRADA','EMX-015-CHICONAUTLA','MOR-006-CUERNAVACA 2',
  'CMX-004-TACUBA','CMX-008-IZAZAGA','CMX-009-CONSTITUYENTES 3',
  'CMX-012-RIO LERMA','EMX-016-CHIMALHUACAN','CMX-014-ROMA NORTE',
  'CMX-018-DOWN TOWN','EMX-024-CUATRO VIENTOS','CMX-034-NARVARTE',
  'CMX-001-PRESA FALCON','CMX-002-HERSCHEL','CMX-011-ARAGÓN-2',
  'CMX-015-ARAGÓN-1','CMX-019-EDIFICIO CASTELAR',
  'CMX-021-SANTA MARIA INSURGENTES','CMX-022-TORRE LATINO',
  'HID-004-TEPEAPULCO','CMX-033-SAN RAFAEL','EMX-017-JOCOTITLAN',
  'CMX-030-LA QUEBRADA',
];

export const MOCK_SERVICES: Service[] = [
  {
    id: 'INST-1486',
    nombre: 'Supervisar el tendido de F.O de la Quebrada',
    fechaCreacion: '2026-05-11T08:26:06',
    creadoPor: 'carlos.martinez@servnet.mx',
    cuadrillaAlias: 'SilentFiber',
    fechaInicio: '2026-05-12T09:00:00',
    status: 'Asignado',
    prioridad: 'Alta',
    estado: 'Nuevo servicio',
    categoria: 'Instalación mayor',
    statusServicio: 'En tiempo',
    tipoTecnologia: 'Fibra óptica',
    actividadARealizar: 'Favor de supervisar el tendido de F.O del pop la quebrada en el punto donde se quedo el dia de ayer',
    ticketWSAS: 'WSAS-9921',
    team: 'OSP CMX',
    razonSocialCliente: 'Servnet S.A. de C.V.',
    direccionCliente: 'Calle Falsa 123',
    pop: 'CMX-030-LA QUEBRADA',
    identificador: 'ID-4421',
    referenciasUbicacion: 'Cerca del metro',
    nombreContacto: 'Carlos Perez',
    telefonoContacto: '5512345678',
    emailContacto: 'carlos@cliente.com',
    qr: 'http://qrcode.com/123',
    color: '#1a73e8',
    esEventoDia: false,
    horaEnCamino: '2026-05-12T08:30:00',
    horaLlegada: '2026-05-12T09:15:00',
    fechaFin: '2026-05-12T17:45:00'
  },
  {
    id: 'INST-1485',
    nombre: 'Tendido de fibra Pop Telmex',
    fechaCreacion: '2026-05-11T09:00:11',
    creadoPor: ' nahum.salgado@servnet.mx',
    cuadrillaAlias: 'Fibonacci',
    fechaInicio: '2026-05-12T09:00:11',
    fechaFin: '2026-05-12T13:00:11',
    status: 'Registrado',
    prioridad: 'Media',
    estado: 'Nuevo servicio',
    categoria: 'Instalación mayor',
    statusServicio: 'En tiempo',
    tipoTecnologia: 'Fibra óptica',
    actividadARealizar: 'Favor de rematar la F.O',
    ticketWSAS: 'WSAS-8812',
    team: 'OSP CMX',
    razonSocialCliente: 'Telmex',
    direccionCliente: 'Av. Insurgentes Sur 1202',
    pop: 'CMX-012-RIO LERMA',
    identificador: 'ID-8812',
    referenciasUbicacion: 'Piso 4',
    nombreContacto: 'Juan Gomez',
    telefonoContacto: '5566778899',
    emailContacto: 'juan@telmex.com',
    qr: 'http://qrcode.com/456',
    color: '#34a853',
    esEventoDia: false
  },
  {
    id: 'ABM-333',
    nombre: 'RECOLECCION MATERIAL MTY',
    fechaCreacion: '2026-05-12T10:00:00',
    creadoPor: 'nahum.salgado@servnet.mx',
    cuadrillaAlias: 'Megatron',
    fechaInicio: '2026-05-12T12:00:00',
    fechaFin: '2026-05-12T15:00:00',
    status: 'Asignado',
    prioridad: 'Baja',
    estado: 'Activo',
    categoria: 'Abasto de materiales',
    statusServicio: 'En tiempo',
    tipoTecnologia: 'Fibra óptica',
    actividadARealizar: 'Carga de carrete',
    ticketWSAS: '',
    team: 'OSP MTY',
    razonSocialCliente: 'Almacen MTY',
    direccionCliente: 'Regio Almacen 1',
    pop: 'MTY-009-GARCÍA',
    identificador: 'ALM-001',
    referenciasUbicacion: '',
    nombreContacto: 'Pedro Regio',
    telefonoContacto: '8112345678',
    emailContacto: 'pedro@mty.mx',
    qr: 'http://',
    color: '#f4b400',
    esEventoDia: false
  }
];

export const MOCK_GAS_REQUESTS: GasRequest[] = [
  {
    id: 'GAS-001',
    tipoSolicitud: 'Normal',
    asignacionUso: 'Unidad móvil',
    solicitante: 'gerardo.gomez@servnet.mx',
    fechaHr: '2026-05-11 09:55:03',
    status: 'Dispersado',
    cuadrilla: 'Britmor',
    tarjeta: '1318820',
    fotoTableroAntes: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&q=80&w=100',
    kilometrajeAntes: 340136,
    cargaMxn: 1000,
    cargaAutorizada: 1000,
    comentarios: ''
  },
  {
    id: 'GAS-002',
    tipoSolicitud: 'Normal',
    asignacionUso: 'Unidad móvil',
    solicitante: 'gerardo.gomez@servnet.mx',
    fechaHr: '2026-05-11 09:54:52',
    status: 'Dispersado',
    cuadrilla: 'Britmor',
    tarjeta: '1318820',
    fotoTableroAntes: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&q=80&w=100',
    kilometrajeAntes: 339915,
    cargaMxn: 800,
    cargaAutorizada: 800,
    comentarios: ''
  },
  {
    id: 'GASPE-001',
    tipoSolicitud: 'Normal',
    asignacionUso: 'Planta de Emergencia',
    solicitante: 'luis.hernandez@servnet.mx',
    fechaHr: '2026-05-11 17:22:39',
    status: 'Cargado/Comprobación',
    cuadrilla: 'Raptor',
    tarjeta: '1420602',
    fotoTableroAntes: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=100',
    kilometrajeAntes: 1,
    cargaMxn: 500,
    cargaAutorizada: 500,
    comentarios: 'Carga para planta emex',
    ticketEfectivale: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&q=80&w=100',
    ticketBomba: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&q=80&w=100',
    bombaCargando: 'https://images.unsplash.com/photo-1545161296-d9c2c241f2ad?auto=format&fit=crop&q=80&w=100',
    fotoTableroDespues: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=100'
  },
  {
    id: 'GAS-003',
    tipoSolicitud: 'Normal',
    asignacionUso: 'Unidad móvil',
    solicitante: 'luis.hernandez@servnet.mx',
    fechaHr: '2026-05-18 15:23:33',
    status: 'Cargado/Comprobación',
    cuadrilla: 'Raptor',
    tarjeta: '1420602',
    fotoTableroAntes: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&q=80&w=100',
    kilometrajeAntes: 1420602,
    cargaMxn: 1200,
    cargaAutorizada: 1200,
    comentarios: 'Ruta foranea',
    ticketEfectivale: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&q=80&w=100',
    ticketBomba: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&q=80&w=100',
    bombaCargando: 'https://images.unsplash.com/photo-1545161296-d9c2c241f2ad?auto=format&fit=crop&q=80&w=100',
    fotoTableroDespues: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&q=80&w=100'
  },
  {
    id: 'GAS-004',
    tipoSolicitud: 'Normal',
    asignacionUso: 'Unidad móvil',
    solicitante: 'luis.hernandez@servnet.mx',
    fechaHr: '2026-05-11 16:24:53',
    status: 'Cargado/Comprobación',
    cuadrilla: 'Raptor',
    tarjeta: '1420602',
    fotoTableroAntes: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&q=80&w=100',
    kilometrajeAntes: 113759,
    cargaMxn: 1000,
    cargaAutorizada: 1000,
    comentarios: '',
    ticketEfectivale: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&q=80&w=100',
    ticketBomba: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&q=80&w=100',
    bombaCargando: 'https://images.unsplash.com/photo-1545161296-d9c2c241f2ad?auto=format&fit=crop&q=80&w=100',
    fotoTableroDespues: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&q=80&w=100'
  },
  {
    id: 'GAS-005',
    tipoSolicitud: 'Normal',
    asignacionUso: 'Unidad móvil',
    solicitante: 'esai.moreno@servnet.mx',
    fechaHr: '2026-04-21 10:21:46',
    status: 'Dispersado',
    cuadrilla: 'Octopus',
    tarjeta: '1318820',
    fotoTableroAntes: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&q=80&w=100',
    kilometrajeAntes: 363046,
    cargaMxn: 900,
    cargaAutorizada: 900,
    comentarios: ''
  },
  {
    id: 'GAS-006',
    tipoSolicitud: 'Normal',
    asignacionUso: 'Unidad móvil',
    solicitante: 'martin.bernal@servnet.mx',
    fechaHr: '2026-05-10 23:09:41',
    status: 'Dispersado',
    cuadrilla: 'SilentFiber',
    tarjeta: '1420602',
    fotoTableroAntes: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&q=80&w=100',
    kilometrajeAntes: 120071,
    cargaMxn: 1500,
    cargaAutorizada: 1500,
    comentarios: 'Carga urgente'
  },
  {
    id: 'GAS-007',
    tipoSolicitud: 'Normal',
    asignacionUso: 'Unidad móvil',
    solicitante: 'enrique.rodriguez@servnet.mx',
    fechaHr: '2026-05-18 09:01:21',
    status: 'Dispersado',
    cuadrilla: 'Kraken',
    tarjeta: '1318818',
    fotoTableroAntes: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&q=80&w=100',
    kilometrajeAntes: 334974,
    cargaMxn: 1000,
    cargaAutorizada: 1000,
    comentarios: ''
  }
];
